from setuptools import setup, find_packages

with open("README.md", "r") as fh:
    long_description = fh.read()

setup(
    name="Apps_package",
    version="0.1.0",
    author="Amirul Iskandar",
    author_email="myruliskandar@gmail.com",
    description="A short description of your package",
    long_description=open('README.md').read(),
    url="",
    packages=find_packages(),
    classifiers=[
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ],
    python_requires='>=3.6',
    install_requires=[
        "altgraph==0.17.3",
        "click==8.1.3",
        "colorama==0.4.6",
        "contourpy==1.0.7",
        "cycler==0.11.0",
        "et-xmlfile==1.1.0",
        "Flask==2.2.3",
        "fonttools==4.38.0",
        "itsdangerous==2.1.2",
        "Jinja2==3.1.2",
        "kiwisolver==1.4.4",
        "MarkupSafe==2.1.2",
        "matplotlib==3.7.0",
        "mplcursors==0.5.2",
        "numpy==1.24.2",
        "openpyxl==3.1.1",
        "packaging==23.0",
        "pandas==1.5.3",
        "pefile==2023.2.7",
        "Pillow==9.4.0",
        "pyinstaller==5.8.0",
        "pyinstaller-hooks-contrib==2023.0",
        "pyparsing==3.0.9",
        "PySimpleGUI==4.60.4",
        "python-dateutil==2.8.2",
        "pytz==2022.7.1",
        "pywin32-ctypes==0.2.0",
        "six==1.16.0",
        "Werkzeug==2.2.3",
    ],
    license='MIT'
)