# Generated by Django 3.2.5 on 2023-03-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchangerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_entity', models.IntegerField(blank=True, null=True)),
                ('rate_base_currency', models.CharField(max_length=255)),
                ('rate_currency', models.CharField(max_length=255)),
                ('rate_date', models.DateField()),
                ('rate_previous_day', models.DateField()),
                ('rate_buy', models.FloatField(blank=True, null=True)),
                ('rate_sell', models.FloatField(blank=True, null=True)),
                ('rate_mid', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_id', models.CharField(max_length=55)),
                ('finance_date', models.DateField()),
                ('finance_request_id', models.IntegerField()),
                ('program_type', models.CharField(max_length=55)),
                ('anchor_party', models.IntegerField()),
                ('counterparty', models.IntegerField()),
                ('due_date', models.DateField()),
                ('invoice_currency', models.CharField(max_length=55)),
                ('invoice_amount', models.IntegerField()),
                ('finance_currency', models.CharField(max_length=55)),
                ('finance_amount', models.IntegerField()),
                ('settlement_currency', models.CharField(max_length=55)),
                ('settlement_amount', models.IntegerField()),
                ('repayment_acc_currency', models.CharField(max_length=55)),
                ('repayment_account', models.CharField(max_length=55)),
                ('interest_type', models.CharField(max_length=55)),
                ('interest_rate_type', models.CharField(max_length=55)),
                ('margin', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('interest_amount', models.IntegerField()),
                ('interest_paid_by', models.CharField(max_length=55)),
                ('own_party_account_info', models.CharField(max_length=55)),
                ('remittance_info', models.CharField(max_length=55)),
                ('status', models.CharField(max_length=55)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_ref', models.CharField(blank=True, max_length=155, null=True)),
                ('stage', models.CharField(blank=True, max_length=155, null=True)),
                ('type', models.CharField(blank=True, max_length=155, null=True)),
                ('currency', models.CharField(blank=True, max_length=155, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=55, null=True)),
                ('account_type', models.CharField(blank=True, max_length=155, null=True)),
                ('base_curreny', models.CharField(blank=True, max_length=155, null=True)),
                ('base_currency_amount', models.IntegerField(blank=True, null=True)),
                ('exch_rate', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
