# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/scip-workflows/',
                'doc_host': 'https://maximlippeveld.github.io',
                'git_url': 'https://github.com/mlippeve/ehv/tree/master/',
                'lib_path': 'scip_workflows'},
  'syms': { 'scip_workflows.common': {},
            'scip_workflows.core': { 'scip_workflows.core.plot_gate_czi': ('core/core.html#plot_gate_czi', 'scip_workflows/core.py'),
                                     'scip_workflows.core.plot_gate_zarr': ('core/core.html#plot_gate_zarr', 'scip_workflows/core.py'),
                                     'scip_workflows.core.plot_gate_zarr_channels': ( 'core/core.html#plot_gate_zarr_channels',
                                                                                      'scip_workflows/core.py')},
            'scip_workflows.masking': { 'scip_workflows.masking.plot_scip_segmentation': ( 'core/threshold_masking.html#plot_scip_segmentation',
                                                                                           'scip_workflows/masking.py')}}}
