# Generated by Django 3.2.7 on 2022-07-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220717_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
