# Generated by Django 3.2.7 on 2022-09-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_workorderservice_bedrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderservice',
            name='bedrooms',
        ),
        migrations.AddField(
            model_name='workorderservice',
            name='configure_bedroom',
            field=models.BooleanField(default=False),
        ),
    ]
