from habit_tracking_app.frames.navigation_menu import Menu
from habit_tracking_app.frames.home_page import Home
from habit_tracking_app.frames.habits_page import Habits
from habit_tracking_app.frames.add_new_habit_page import AddNewHabit
from habit_tracking_app.frames.edit_habit_page import EditHabit
from habit_tracking_app.frames.delete_habit_page import DeleteHabit
from habit_tracking_app.frames.mark_as_completed_page import MarkAsCompleted
from habit_tracking_app.frames.analytics_page import Analytics
from habit_tracking_app.frames.settings_page import Settings
from habit_tracking_app.frames.reset_data_page import ResetData
from habit_tracking_app.frames.exit_page import Exit
