"""k8scheck -- a Kubernetes integration test framework in Python."""
__title__ = "k8scheck"
__description__ = "A Kubernetes integration test framework in Python."
__author__ = "Terry Drisi (originally Vapor IO)"
__author_email__ = "k8scheck@3si.me"
__url__ = "https://github.com/3sIT/k8scheck"
__license__ = "GNU General Public License v3.0"
