
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-03T20:46:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7101160967a714a961ce7405ebfd85490758f30",
 "version": "1.18.2.post0.dev160"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
