
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-04T12:34:51-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "82b40aa24192a287bff2d0b4e92e6ea48cb8a093",
 "version": "0.0.159"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
