
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-03T01:05:00+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "da7687f978faf5624f5d1f4f7b5ee32b6c06064a",
 "version": "2.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
