
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-06T06:04:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "db7556a51c72fac74c730c45c8a979958e95eaf7",
 "version": "2023.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
