
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-03T20:14:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d3643b80159fa4373cdd4f260e1b003fc74aff9",
 "version": "0.3.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
