
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-02T05:22:57-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "14b72222fa587012c7e5b4e27cc82572ab4a3edd",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
