
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-06T05:42:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a15cce8c27993845681909cf36d1185177b179ca",
 "version": "1.18.2.post0.dev167"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
