# Generated by Django 4.1.7 on 2023-03-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("wagtailperson", "0006_auto_20200416_1603"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["name"],
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
        ),
        migrations.AlterModelOptions(
            name="personindexpage",
            options={
                "verbose_name": "Persons Index Page",
                "verbose_name_plural": "Persons Index Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="personpage",
            options={
                "ordering": ["title"],
                "verbose_name": "Person page",
                "verbose_name_plural": "Person pages",
            },
        ),
        migrations.AlterField(
            model_name="persontag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="taggit.tag",
            ),
        ),
    ]
