
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-06T06:03:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5f957acef197c89c8c94d33a14f256df53ebf49",
 "version": "1.18.2.post0.dev170"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
