# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: farm_ng/canbus/canbus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x66\x61rm_ng/canbus/canbus.proto\x12\x14\x66\x61rm_ng.canbus.proto\"\x15\n\x13StreamCanbusRequest\"N\n\x11StreamCanbusReply\x12\x39\n\x08messages\x18\x01 \x01(\x0b\x32\'.farm_ng.canbus.proto.RawCanbusMessages\"S\n\x18SendCanbusMessageRequest\x12\x37\n\x07message\x18\x01 \x01(\x0b\x32&.farm_ng.canbus.proto.RawCanbusMessage\")\n\x16SendCanbusMessageReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"g\n\x10RawCanbusMessage\x12\r\n\x05stamp\x18\x01 \x01(\x01\x12\n\n\x02id\x18\x02 \x01(\r\x12\r\n\x05\x65rror\x18\x03 \x01(\x08\x12\x1b\n\x13remote_transmission\x18\x04 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"M\n\x11RawCanbusMessages\x12\x38\n\x08messages\x18\x01 \x03(\x0b\x32&.farm_ng.canbus.proto.RawCanbusMessage\"\x1a\n\x18StreamMotorStatesRequest\"{\n\nMotorState\x12\r\n\x05stamp\x18\x01 \x01(\x01\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0e\n\x06status\x18\x03 \x01(\r\x12\x0b\n\x03rpm\x18\x04 \x01(\x05\x12\x0f\n\x07voltage\x18\x05 \x01(\x01\x12\x0f\n\x07\x63urrent\x18\x06 \x01(\x01\x12\x13\n\x0btemperature\x18\x07 \x01(\x05\"J\n\x16StreamMotorStatesReply\x12\x30\n\x06motors\x18\x01 \x03(\x0b\x32 .farm_ng.canbus.proto.MotorState2\xef\x02\n\rCanbusService\x12n\n\x14streamCanbusMessages\x12).farm_ng.canbus.proto.StreamCanbusRequest\x1a\'.farm_ng.canbus.proto.StreamCanbusReply\"\x00\x30\x01\x12w\n\x11sendCanbusMessage\x12..farm_ng.canbus.proto.SendCanbusMessageRequest\x1a,.farm_ng.canbus.proto.SendCanbusMessageReply\"\x00(\x01\x30\x01\x12u\n\x11streamMotorStates\x12..farm_ng.canbus.proto.StreamMotorStatesRequest\x1a,.farm_ng.canbus.proto.StreamMotorStatesReply\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'farm_ng.canbus.canbus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STREAMCANBUSREQUEST._serialized_start=53
  _STREAMCANBUSREQUEST._serialized_end=74
  _STREAMCANBUSREPLY._serialized_start=76
  _STREAMCANBUSREPLY._serialized_end=154
  _SENDCANBUSMESSAGEREQUEST._serialized_start=156
  _SENDCANBUSMESSAGEREQUEST._serialized_end=239
  _SENDCANBUSMESSAGEREPLY._serialized_start=241
  _SENDCANBUSMESSAGEREPLY._serialized_end=282
  _RAWCANBUSMESSAGE._serialized_start=284
  _RAWCANBUSMESSAGE._serialized_end=387
  _RAWCANBUSMESSAGES._serialized_start=389
  _RAWCANBUSMESSAGES._serialized_end=466
  _STREAMMOTORSTATESREQUEST._serialized_start=468
  _STREAMMOTORSTATESREQUEST._serialized_end=494
  _MOTORSTATE._serialized_start=496
  _MOTORSTATE._serialized_end=619
  _STREAMMOTORSTATESREPLY._serialized_start=621
  _STREAMMOTORSTATESREPLY._serialized_end=695
  _CANBUSSERVICE._serialized_start=698
  _CANBUSSERVICE._serialized_end=1065
# @@protoc_insertion_point(module_scope)
