
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-06T07:52:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b739f74a82ce3c8cac066e6d4b92b38244cede3",
 "version": "1.18.2.post0.dev182"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
