
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-23T21:48:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "05ca6820215a76f087f78091d0bc4b45a330b2d9",
 "version": "0.5.9.dev20230303"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
