
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-02T20:42:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6823f6d27c7dc8aee0928b88a2e51ee320ceafc4",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
