# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_basic_how = {
    'am looking for the': 1,
 'am trying to find': 1,
 'can i': 1,
 'can i find the': 1,
 'can i get to': 1,
 'can i still': 1,
 'can you give me': 1,
 'can you help me': 2,
 'can you inform me': 1,
 'can you point me': 1,
 'can you tell me': 4,
 'could give me some': 2,
 'do i': 2,
 'do i send': 1,
 'do we do when': 1,
 'do you suggest i': 1,
 'else can i do': 1,
 'give me directions to': 1,
 'give me some directions': 2,
 'go to find the': 1,
 'help me find the': 1,
 'help me locate the': 1,
 'how can i': 1,
 'how can i do': 1,
 'how can i get': 1,
 'how do i': 1,
 'how do i find': 1,
 'how do you do': 1,
 'how do you suggest': 1,
 'how else can i': 1,
 'how is': 1,
 'how long': 1,
 'how long will it': 1,
 'how many': 1,
 'how might i': 1,
 'how might i go': 1,
 'how much': 1,
 'how much is': 1,
 'how much money': 1,
 'how much money is': 1,
 'how to get to': 1,
 'i am looking for': 1,
 'i am trying to': 1,
 'i can find the': 1,
 'i get to the': 1,
 'i need to find': 1,
 'i would like it': 1,
 "i'd like it if": 1,
 'if you could give': 2,
 'inform me where i': 1,
 'is it possible': 1,
 'is it possible to': 1,
 'is the date': 1,
 'is the due date': 1,
 'is there a': 1,
 'is there an': 1,
 'it if you could': 2,
 'like it if you': 2,
 'long will it take': 1,
 'me directions to the': 1,
 'me how to get': 1,
 'me some directions to': 2,
 'me the way to': 1,
 'me where i can': 1,
 'me where to go': 1,
 'might i go about': 1,
 'need to find the': 1,
 'point me towards the': 1,
 'some directions to the': 2,
 'tell me how to': 1,
 'tell me the way': 1,
 'tell me where the': 1,
 'tell me where to': 1,
 'the way to the': 1,
 'to get to the': 1,
 'to go to find': 1,
 'trying to find the': 1,
 'what do we do': 1,
 'what does': 1,
 'what happens if': 1,
 'what is': 1,
 'what is a': 1,
 'what is an': 1,
 'what is the': 1,
 'when is the': 1,
 'when is the due': 1,
 'where are': 1,
 'where can i find': 1,
 'where do': 1,
 'where do i': 1,
 'where i can find': 1,
 'where is': 1,
 'where is the': 1,
 'where to go to': 1,
 'who do': 1,
 'would like it if': 1,
 'you could give me': 2,
 'you give me directions': 1,
 'you help me find': 1,
 'you help me locate': 1,
 'you inform me where': 1,
 'you point me towards': 1,
 'you tell me how': 1,
 'you tell me the': 1,
 'you tell me where': 2
}
