# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_basic_where = {
    'am looking for the': 11,
 'am trying to find': 11,
 'can i': 11,
 'can i find the': 11,
 'can i get to': 11,
 'can i still': 11,
 'can you give me': 11,
 'can you help me': 22,
 'can you inform me': 11,
 'can you point me': 11,
 'can you tell me': 44,
 'could give me some': 22,
 'do i': 22,
 'do i send': 11,
 'do we do when': 11,
 'do you suggest i': 11,
 'else can i do': 11,
 'give me directions to': 11,
 'give me some directions': 22,
 'go to find the': 11,
 'help me find the': 11,
 'help me locate the': 11,
 'how can i': 11,
 'how can i do': 11,
 'how can i get': 11,
 'how do i': 11,
 'how do i find': 11,
 'how do you do': 11,
 'how do you suggest': 11,
 'how else can i': 11,
 'how is': 11,
 'how long': 11,
 'how long will it': 11,
 'how many': 11,
 'how might i': 11,
 'how might i go': 11,
 'how much': 11,
 'how much is': 11,
 'how much money': 11,
 'how much money is': 11,
 'how to get to': 11,
 'i am looking for': 11,
 'i am trying to': 11,
 'i can find the': 11,
 'i get to the': 11,
 'i need to find': 11,
 'i would like it': 11,
 "i'd like it if": 11,
 'if you could give': 22,
 'inform me where i': 11,
 'is it possible': 11,
 'is it possible to': 11,
 'is the date': 11,
 'is the due date': 11,
 'is there a': 11,
 'is there an': 11,
 'it if you could': 22,
 'like it if you': 22,
 'long will it take': 11,
 'me directions to the': 11,
 'me how to get': 11,
 'me some directions to': 22,
 'me the way to': 11,
 'me where i can': 11,
 'me where to go': 11,
 'might i go about': 11,
 'need to find the': 11,
 'point me towards the': 11,
 'some directions to the': 22,
 'tell me how to': 11,
 'tell me the way': 11,
 'tell me where the': 11,
 'tell me where to': 11,
 'the way to the': 11,
 'to get to the': 11,
 'to go to find': 11,
 'trying to find the': 11,
 'what do we do': 11,
 'what does': 11,
 'what happens if': 11,
 'what is': 11,
 'what is a': 11,
 'what is an': 11,
 'what is the': 11,
 'when is the': 11,
 'when is the due': 11,
 'where are': 11,
 'where can i find': 11,
 'where do': 11,
 'where do i': 11,
 'where i can find': 11,
 'where is': 11,
 'where is the': 11,
 'where to go to': 11,
 'who do': 11,
 'would like it if': 11,
 'you could give me': 22,
 'you give me directions': 11,
 'you help me find': 11,
 'you help me locate': 11,
 'you inform me where': 11,
 'you point me towards': 11,
 'you tell me how': 11,
 'you tell me the': 11,
 'you tell me where': 22
}
