# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_hints = {
    'am looking for the': ['WHERE_LOCATION'],
 'am trying to find': ['WHERE_LOCATION'],
 'can i': ['EXISTENTIAL'],
 'can i find the': ['WHERE_LOCATION'],
 'can i get to': ['WHERE_LOCATION'],
 'can i still': ['EXISTENTIAL'],
 'can you give me': ['WHERE_LOCATION'],
 'can you help me': ['WHERE_LOCATION'],
 'can you inform me': ['WHERE_LOCATION'],
 'can you point me': ['WHERE_LOCATION'],
 'can you tell me': ['WHERE_LOCATION'],
 'could give me some': ['WHERE_LOCATION'],
 'do i': ['WHERE_LOCATION', 'WHAT_WHO'],
 'do i send': ['WHERE_LOCATION'],
 'do we do when': ['WHAT_WHEN'],
 'do you suggest i': ['BASIC_HOW'],
 'else can i do': ['BASIC_HOW'],
 'give me directions to': ['WHERE_LOCATION'],
 'give me some directions': ['WHERE_LOCATION'],
 'go to find the': ['WHERE_LOCATION'],
 'help me find the': ['WHERE_LOCATION'],
 'help me locate the': ['WHERE_LOCATION'],
 'how can i': ['BASIC_HOW'],
 'how can i do': ['BASIC_HOW'],
 'how can i get': ['WHERE_LOCATION'],
 'how do i': ['BASIC_HOW'],
 'how do i find': ['BASIC_HOW'],
 'how do you do': ['BASIC_HOW'],
 'how do you suggest': ['BASIC_HOW'],
 'how else can i': ['BASIC_HOW'],
 'how is': ['BASIC_HOW'],
 'how long': ['HOW_LONG_TIME'],
 'how long will it': ['HOW_LONG_TIME'],
 'how many': ['HOW_MANY'],
 'how might i': ['BASIC_HOW'],
 'how might i go': ['BASIC_HOW'],
 'how much': ['HOW_MANY'],
 'how much is': ['HOW_MANY'],
 'how much money': ['HOW_MUCH_MONEY'],
 'how much money is': ['HOW_MUCH_MONEY'],
 'how to get to': ['WHERE_LOCATION'],
 'i am looking for': ['WHERE_LOCATION'],
 'i am trying to': ['WHERE_LOCATION'],
 'i can find the': ['WHERE_LOCATION'],
 'i get to the': ['WHERE_LOCATION'],
 'i need to find': ['WHERE_LOCATION'],
 'i would like it': ['WHERE_LOCATION'],
 "i'd like it if": ['WHERE_LOCATION'],
 'if you could give': ['WHERE_LOCATION'],
 'inform me where i': ['WHERE_LOCATION'],
 'is it possible': ['EXISTENTIAL'],
 'is it possible to': ['EXISTENTIAL'],
 'is the date': ['WHEN_DATE'],
 'is the due date': ['WHEN_DATE'],
 'is there a': ['EXISTENTIAL'],
 'is there an': ['EXISTENTIAL'],
 'it if you could': ['WHERE_LOCATION'],
 'like it if you': ['WHERE_LOCATION'],
 'long will it take': ['HOW_LONG_TIME'],
 'me directions to the': ['WHERE_LOCATION'],
 'me how to get': ['WHERE_LOCATION'],
 'me some directions to': ['WHERE_LOCATION'],
 'me the way to': ['WHERE_LOCATION'],
 'me where i can': ['WHERE_LOCATION'],
 'me where to go': ['WHERE_LOCATION'],
 'might i go about': ['BASIC_HOW'],
 'need to find the': ['WHERE_LOCATION'],
 'point me towards the': ['WHERE_LOCATION'],
 'some directions to the': ['WHERE_LOCATION'],
 'tell me how to': ['WHERE_LOCATION'],
 'tell me the way': ['WHERE_LOCATION'],
 'tell me where the': ['WHERE_LOCATION'],
 'tell me where to': ['WHERE_LOCATION'],
 'the way to the': ['WHERE_LOCATION'],
 'to get to the': ['WHERE_LOCATION'],
 'to go to find': ['WHERE_LOCATION'],
 'trying to find the': ['WHERE_LOCATION'],
 'what do we do': ['WHAT_WHEN'],
 'what does': ['BASIC_WHAT'],
 'what happens if': ['WHAT_WILL'],
 'what is': ['BASIC_WHAT'],
 'what is a': ['WHAT_WHO'],
 'what is an': ['WHAT_WHO'],
 'what is the': ['BASIC_WHAT'],
 'when is the': ['WHEN_DATE'],
 'when is the due': ['WHEN_DATE'],
 'where are': ['BASIC_WHERE'],
 'where can i find': ['WHERE_LOCATION'],
 'where do': ['WHERE_LOCATION'],
 'where do i': ['WHERE_LOCATION'],
 'where i can find': ['WHERE_LOCATION'],
 'where is': ['WHERE_LOCATION'],
 'where is the': ['WHERE_LOCATION'],
 'where to go to': ['WHERE_LOCATION'],
 'who do': ['WHAT_WHO'],
 'would like it if': ['WHERE_LOCATION'],
 'you could give me': ['WHERE_LOCATION'],
 'you give me directions': ['WHERE_LOCATION'],
 'you help me find': ['WHERE_LOCATION'],
 'you help me locate': ['WHERE_LOCATION'],
 'you inform me where': ['WHERE_LOCATION'],
 'you point me towards': ['WHERE_LOCATION'],
 'you tell me how': ['WHERE_LOCATION'],
 'you tell me the': ['WHERE_LOCATION'],
 'you tell me where': ['WHERE_LOCATION']
}
