# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_how_many = {
    'am looking for the': 5,
 'am trying to find': 5,
 'can i': 5,
 'can i find the': 5,
 'can i get to': 5,
 'can i still': 5,
 'can you give me': 5,
 'can you help me': 10,
 'can you inform me': 5,
 'can you point me': 5,
 'can you tell me': 20,
 'could give me some': 10,
 'do i': 10,
 'do i send': 5,
 'do we do when': 5,
 'do you suggest i': 5,
 'else can i do': 5,
 'give me directions to': 5,
 'give me some directions': 10,
 'go to find the': 5,
 'help me find the': 5,
 'help me locate the': 5,
 'how can i': 5,
 'how can i do': 5,
 'how can i get': 5,
 'how do i': 5,
 'how do i find': 5,
 'how do you do': 5,
 'how do you suggest': 5,
 'how else can i': 5,
 'how is': 5,
 'how long': 5,
 'how long will it': 5,
 'how many': 5,
 'how might i': 5,
 'how might i go': 5,
 'how much': 5,
 'how much is': 5,
 'how much money': 5,
 'how much money is': 5,
 'how to get to': 5,
 'i am looking for': 5,
 'i am trying to': 5,
 'i can find the': 5,
 'i get to the': 5,
 'i need to find': 5,
 'i would like it': 5,
 "i'd like it if": 5,
 'if you could give': 10,
 'inform me where i': 5,
 'is it possible': 5,
 'is it possible to': 5,
 'is the date': 5,
 'is the due date': 5,
 'is there a': 5,
 'is there an': 5,
 'it if you could': 10,
 'like it if you': 10,
 'long will it take': 5,
 'me directions to the': 5,
 'me how to get': 5,
 'me some directions to': 10,
 'me the way to': 5,
 'me where i can': 5,
 'me where to go': 5,
 'might i go about': 5,
 'need to find the': 5,
 'point me towards the': 5,
 'some directions to the': 10,
 'tell me how to': 5,
 'tell me the way': 5,
 'tell me where the': 5,
 'tell me where to': 5,
 'the way to the': 5,
 'to get to the': 5,
 'to go to find': 5,
 'trying to find the': 5,
 'what do we do': 5,
 'what does': 5,
 'what happens if': 5,
 'what is': 5,
 'what is a': 5,
 'what is an': 5,
 'what is the': 5,
 'when is the': 5,
 'when is the due': 5,
 'where are': 5,
 'where can i find': 5,
 'where do': 5,
 'where do i': 5,
 'where i can find': 5,
 'where is': 5,
 'where is the': 5,
 'where to go to': 5,
 'who do': 5,
 'would like it if': 5,
 'you could give me': 10,
 'you give me directions': 5,
 'you help me find': 5,
 'you help me locate': 5,
 'you inform me where': 5,
 'you point me towards': 5,
 'you tell me how': 5,
 'you tell me the': 5,
 'you tell me where': 10
}
