# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_how_much_money = {
    'am looking for the': 6,
 'am trying to find': 6,
 'can i': 6,
 'can i find the': 6,
 'can i get to': 6,
 'can i still': 6,
 'can you give me': 6,
 'can you help me': 12,
 'can you inform me': 6,
 'can you point me': 6,
 'can you tell me': 24,
 'could give me some': 12,
 'do i': 12,
 'do i send': 6,
 'do we do when': 6,
 'do you suggest i': 6,
 'else can i do': 6,
 'give me directions to': 6,
 'give me some directions': 12,
 'go to find the': 6,
 'help me find the': 6,
 'help me locate the': 6,
 'how can i': 6,
 'how can i do': 6,
 'how can i get': 6,
 'how do i': 6,
 'how do i find': 6,
 'how do you do': 6,
 'how do you suggest': 6,
 'how else can i': 6,
 'how is': 6,
 'how long': 6,
 'how long will it': 6,
 'how many': 6,
 'how might i': 6,
 'how might i go': 6,
 'how much': 6,
 'how much is': 6,
 'how much money': 6,
 'how much money is': 6,
 'how to get to': 6,
 'i am looking for': 6,
 'i am trying to': 6,
 'i can find the': 6,
 'i get to the': 6,
 'i need to find': 6,
 'i would like it': 6,
 "i'd like it if": 6,
 'if you could give': 12,
 'inform me where i': 6,
 'is it possible': 6,
 'is it possible to': 6,
 'is the date': 6,
 'is the due date': 6,
 'is there a': 6,
 'is there an': 6,
 'it if you could': 12,
 'like it if you': 12,
 'long will it take': 6,
 'me directions to the': 6,
 'me how to get': 6,
 'me some directions to': 12,
 'me the way to': 6,
 'me where i can': 6,
 'me where to go': 6,
 'might i go about': 6,
 'need to find the': 6,
 'point me towards the': 6,
 'some directions to the': 12,
 'tell me how to': 6,
 'tell me the way': 6,
 'tell me where the': 6,
 'tell me where to': 6,
 'the way to the': 6,
 'to get to the': 6,
 'to go to find': 6,
 'trying to find the': 6,
 'what do we do': 6,
 'what does': 6,
 'what happens if': 6,
 'what is': 6,
 'what is a': 6,
 'what is an': 6,
 'what is the': 6,
 'when is the': 6,
 'when is the due': 6,
 'where are': 6,
 'where can i find': 6,
 'where do': 6,
 'where do i': 6,
 'where i can find': 6,
 'where is': 6,
 'where is the': 6,
 'where to go to': 6,
 'who do': 6,
 'would like it if': 6,
 'you could give me': 12,
 'you give me directions': 6,
 'you help me find': 6,
 'you help me locate': 6,
 'you inform me where': 6,
 'you point me towards': 6,
 'you tell me how': 6,
 'you tell me the': 6,
 'you tell me where': 12
}
