# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_what_will = {
    'am looking for the': 9,
 'am trying to find': 9,
 'can i': 9,
 'can i find the': 9,
 'can i get to': 9,
 'can i still': 9,
 'can you give me': 9,
 'can you help me': 18,
 'can you inform me': 9,
 'can you point me': 9,
 'can you tell me': 36,
 'could give me some': 18,
 'do i': 18,
 'do i send': 9,
 'do we do when': 9,
 'do you suggest i': 9,
 'else can i do': 9,
 'give me directions to': 9,
 'give me some directions': 18,
 'go to find the': 9,
 'help me find the': 9,
 'help me locate the': 9,
 'how can i': 9,
 'how can i do': 9,
 'how can i get': 9,
 'how do i': 9,
 'how do i find': 9,
 'how do you do': 9,
 'how do you suggest': 9,
 'how else can i': 9,
 'how is': 9,
 'how long': 9,
 'how long will it': 9,
 'how many': 9,
 'how might i': 9,
 'how might i go': 9,
 'how much': 9,
 'how much is': 9,
 'how much money': 9,
 'how much money is': 9,
 'how to get to': 9,
 'i am looking for': 9,
 'i am trying to': 9,
 'i can find the': 9,
 'i get to the': 9,
 'i need to find': 9,
 'i would like it': 9,
 "i'd like it if": 9,
 'if you could give': 18,
 'inform me where i': 9,
 'is it possible': 9,
 'is it possible to': 9,
 'is the date': 9,
 'is the due date': 9,
 'is there a': 9,
 'is there an': 9,
 'it if you could': 18,
 'like it if you': 18,
 'long will it take': 9,
 'me directions to the': 9,
 'me how to get': 9,
 'me some directions to': 18,
 'me the way to': 9,
 'me where i can': 9,
 'me where to go': 9,
 'might i go about': 9,
 'need to find the': 9,
 'point me towards the': 9,
 'some directions to the': 18,
 'tell me how to': 9,
 'tell me the way': 9,
 'tell me where the': 9,
 'tell me where to': 9,
 'the way to the': 9,
 'to get to the': 9,
 'to go to find': 9,
 'trying to find the': 9,
 'what do we do': 9,
 'what does': 9,
 'what happens if': 9,
 'what is': 9,
 'what is a': 9,
 'what is an': 9,
 'what is the': 9,
 'when is the': 9,
 'when is the due': 9,
 'where are': 9,
 'where can i find': 9,
 'where do': 9,
 'where do i': 9,
 'where i can find': 9,
 'where is': 9,
 'where is the': 9,
 'where to go to': 9,
 'who do': 9,
 'would like it if': 9,
 'you could give me': 18,
 'you give me directions': 9,
 'you help me find': 9,
 'you help me locate': 9,
 'you inform me where': 9,
 'you point me towards': 9,
 'you tell me how': 9,
 'you tell me the': 9,
 'you tell me where': 18
}
