/* File: polsysmodule.c
 * This file is auto-generated with f2py (version:1.23.1).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Jul 19 12:31:09 2022
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *polsys_error;
static PyObject *polsys_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef struct {double r,i;} complex_double;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"polsys.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

#define pyobj_from_double1(v) (PyFloat_FromDouble(v))
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define pyobj_from_complex_double1(v) (PyComplex_FromDoubles(v.r,v.i))
#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(polsys_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: PyArray_SETITEM(arr,PyArray_DATA(arr),pyobj_from_ ## ctype ## 1(*v)); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (PyArray_DESCR(arr)->type==typecode)  {*(ctype *)(PyArray_DATA(arr))=*v; return 1;}\
        switch (PyArray_TYPE(arr)) {\
                case NPY_DOUBLE: *(npy_double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_INT: *(npy_int *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONG: *(npy_long *)(PyArray_DATA(arr))=*v; break;\
                case NPY_FLOAT: *(npy_float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CDOUBLE: *(npy_double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CFLOAT: *(npy_float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BOOL: *(npy_bool *)(PyArray_DATA(arr))=(*v!=0); break;\
                case NPY_UBYTE: *(npy_ubyte *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BYTE: *(npy_byte *)(PyArray_DATA(arr))=*v; break;\
                case NPY_SHORT: *(npy_short *)(PyArray_DATA(arr))=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(PyArray_DATA(arr))=*v; break;\
                case NPY_UINT: *(npy_uint *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_OBJECT: PyArray_SETITEM(arr, PyArray_DATA(arr), pyobj_from_ ## ctype ## 1(*v)); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = polsys_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}

static int try_pyarr_from_double(PyObject* obj,double* v) {
    TRYPYARRAYTEMPLATE(double,'d');
}

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = polsys_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(dhorner_mv,DHORNER_MV)(int*,int*,int*,complex_double*,complex_double*,complex_double*);
extern void F_FUNC_US(target_system_user,TARGET_SYSTEM_USER)(int*,complex_double*,complex_double*,complex_double*,complex_double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* dhorner_mv *********************************/
static char doc_f2py_rout_polsys_dhorner_mv[] = "\
p,dp = dhorner_mv(eq,ncoef,x0,[nv])\n\nWrapper for ``dhorner_mv``.\
\n\nParameters\n----------\n"
"eq : input int\n"
"ncoef : input int\n"
"x0 : input rank-1 array('D') with bounds (nv)\n"
"\nOther Parameters\n----------------\n"
"nv : input int, optional\n    Default: len(x0)\n"
"\nReturns\n-------\n"
"p : complex\n"
"dp : rank-1 array('D') with bounds (nv)";
/* extern void F_FUNC_US(dhorner_mv,DHORNER_MV)(int*,int*,int*,complex_double*,complex_double*,complex_double*); */
static PyObject *f2py_rout_polsys_dhorner_mv(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,complex_double*,complex_double*,complex_double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int eq = 0;
    PyObject *eq_capi = Py_None;
    int ncoef = 0;
    PyObject *ncoef_capi = Py_None;
    int nv = 0;
    PyObject *nv_capi = Py_None;
    complex_double *x0 = NULL;
    npy_intp x0_Dims[1] = {-1};
    const int x0_Rank = 1;
    PyArrayObject *capi_x0_tmp = NULL;
    int capi_x0_intent = 0;
    PyObject *x0_capi = Py_None;
    complex_double p;
    PyObject *p_capi = Py_None;
    complex_double *dp = NULL;
    npy_intp dp_Dims[1] = {-1};
    const int dp_Rank = 1;
    PyArrayObject *capi_dp_tmp = NULL;
    int capi_dp_intent = 0;
    static char *capi_kwlist[] = {"eq","ncoef","x0","nv",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:polsys.dhorner_mv",\
        capi_kwlist,&eq_capi,&ncoef_capi,&x0_capi,&nv_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable eq */
        f2py_success = int_from_pyobj(&eq,eq_capi,"polsys.dhorner_mv() 1st argument (eq) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ncoef */
        f2py_success = int_from_pyobj(&ncoef,ncoef_capi,"polsys.dhorner_mv() 2nd argument (ncoef) can't be converted to int");
    if (f2py_success) {
    /* Processing variable x0 */
    ;
    capi_x0_intent |= F2PY_INTENT_IN;
    capi_x0_tmp = array_from_pyobj(NPY_CDOUBLE,x0_Dims,x0_Rank,capi_x0_intent,x0_capi);
    if (capi_x0_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting 3rd argument `x0' of polsys.dhorner_mv to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        x0 = (complex_double *)(PyArray_DATA(capi_x0_tmp));

    /* Processing variable p */
    /* Processing variable nv */
    if (nv_capi == Py_None) nv = len(x0); else
        f2py_success = int_from_pyobj(&nv,nv_capi,"polsys.dhorner_mv() 1st keyword (nv) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(x0)>=nv,"len(x0)>=nv","1st keyword nv","dhorner_mv:nv=%d",nv) {
    /* Processing variable dp */
    dp_Dims[0]=nv;
    capi_dp_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    capi_dp_tmp = array_from_pyobj(NPY_CDOUBLE,dp_Dims,dp_Rank,capi_dp_intent,Py_None);
    if (capi_dp_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting hidden `dp' of polsys.dhorner_mv to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        dp = (complex_double *)(PyArray_DATA(capi_dp_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&eq,&ncoef,&nv,x0,&p,dp);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
    p_capi = pyobj_from_complex_double1(p);
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NN",p_capi,capi_dp_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /*if (capi_dp_tmp == NULL) ... else of dp*/
    /* End of cleaning variable dp */
    } /*CHECKSCALAR(len(x0)>=nv)*/
    } /*if (f2py_success) of nv*/
    /* End of cleaning variable nv */
    /* End of cleaning variable p */
    if((PyObject *)capi_x0_tmp!=x0_capi) {
        Py_XDECREF(capi_x0_tmp); }
    }  /*if (capi_x0_tmp == NULL) ... else of x0*/
    /* End of cleaning variable x0 */
    } /*if (f2py_success) of ncoef*/
    /* End of cleaning variable ncoef */
    } /*if (f2py_success) of eq*/
    /* End of cleaning variable eq */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of dhorner_mv *****************************/

/***************************** target_system_user *****************************/
static char doc_f2py_rout_polsys_target_system_user[] = "\
f,df = target_system_user(proj_coef,xc,[n])\n\nWrapper for ``target_system_user``.\
\n\nParameters\n----------\n"
"proj_coef : input rank-1 array('D') with bounds (1 + n)\n"
"xc : input rank-1 array('D') with bounds (1 + n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: (len(proj_coef)-1)\n"
"\nReturns\n-------\n"
"f : rank-1 array('D') with bounds (n)\n"
"df : rank-2 array('D') with bounds (n,1 + n)";
/* extern void F_FUNC_US(target_system_user,TARGET_SYSTEM_USER)(int*,complex_double*,complex_double*,complex_double*,complex_double*); */
static PyObject *f2py_rout_polsys_target_system_user(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,complex_double*,complex_double*,complex_double*,complex_double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int n = 0;
    PyObject *n_capi = Py_None;
    complex_double *proj_coef = NULL;
    npy_intp proj_coef_Dims[1] = {-1};
    const int proj_coef_Rank = 1;
    PyArrayObject *capi_proj_coef_tmp = NULL;
    int capi_proj_coef_intent = 0;
    PyObject *proj_coef_capi = Py_None;
    complex_double *xc = NULL;
    npy_intp xc_Dims[1] = {-1};
    const int xc_Rank = 1;
    PyArrayObject *capi_xc_tmp = NULL;
    int capi_xc_intent = 0;
    PyObject *xc_capi = Py_None;
    complex_double *f = NULL;
    npy_intp f_Dims[1] = {-1};
    const int f_Rank = 1;
    PyArrayObject *capi_f_tmp = NULL;
    int capi_f_intent = 0;
    complex_double *df = NULL;
    npy_intp df_Dims[2] = {-1, -1};
    const int df_Rank = 2;
    PyArrayObject *capi_df_tmp = NULL;
    int capi_df_intent = 0;
    static char *capi_kwlist[] = {"proj_coef","xc","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|O:polsys.target_system_user",\
        capi_kwlist,&proj_coef_capi,&xc_capi,&n_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable proj_coef */
    ;
    capi_proj_coef_intent |= F2PY_INTENT_IN;
    capi_proj_coef_tmp = array_from_pyobj(NPY_CDOUBLE,proj_coef_Dims,proj_coef_Rank,capi_proj_coef_intent,proj_coef_capi);
    if (capi_proj_coef_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting 1st argument `proj_coef' of polsys.target_system_user to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        proj_coef = (complex_double *)(PyArray_DATA(capi_proj_coef_tmp));

    /* Processing variable n */
    if (n_capi == Py_None) n = (len(proj_coef)-1); else
        f2py_success = int_from_pyobj(&n,n_capi,"polsys.target_system_user() 1st keyword (n) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR((len(proj_coef)-1)>=n,"(len(proj_coef)-1)>=n","1st keyword n","target_system_user:n=%d",n) {
    /* Processing variable xc */
    xc_Dims[0]=1 + n;
    capi_xc_intent |= F2PY_INTENT_IN;
    capi_xc_tmp = array_from_pyobj(NPY_CDOUBLE,xc_Dims,xc_Rank,capi_xc_intent,xc_capi);
    if (capi_xc_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting 2nd argument `xc' of polsys.target_system_user to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        xc = (complex_double *)(PyArray_DATA(capi_xc_tmp));

    /* Processing variable f */
    f_Dims[0]=n;
    capi_f_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    capi_f_tmp = array_from_pyobj(NPY_CDOUBLE,f_Dims,f_Rank,capi_f_intent,Py_None);
    if (capi_f_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting hidden `f' of polsys.target_system_user to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        f = (complex_double *)(PyArray_DATA(capi_f_tmp));

    /* Processing variable df */
    df_Dims[0]=n,df_Dims[1]=1 + n;
    capi_df_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    capi_df_tmp = array_from_pyobj(NPY_CDOUBLE,df_Dims,df_Rank,capi_df_intent,Py_None);
    if (capi_df_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting hidden `df' of polsys.target_system_user to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        df = (complex_double *)(PyArray_DATA(capi_df_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&n,proj_coef,xc,f,df);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NN",capi_f_tmp,capi_df_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /*if (capi_df_tmp == NULL) ... else of df*/
    /* End of cleaning variable df */
    }  /*if (capi_f_tmp == NULL) ... else of f*/
    /* End of cleaning variable f */
    if((PyObject *)capi_xc_tmp!=xc_capi) {
        Py_XDECREF(capi_xc_tmp); }
    }  /*if (capi_xc_tmp == NULL) ... else of xc*/
    /* End of cleaning variable xc */
    } /*CHECKSCALAR((len(proj_coef)-1)>=n)*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    if((PyObject *)capi_proj_coef_tmp!=proj_coef_capi) {
        Py_XDECREF(capi_proj_coef_tmp); }
    }  /*if (capi_proj_coef_tmp == NULL) ... else of proj_coef*/
    /* End of cleaning variable proj_coef */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************* end of target_system_user *************************/

/********************************* init_steps *********************************/
static char doc_f2py_rout_polsys_polystats_init_steps[] = "\
steps = init_steps(deg)\n\nWrapper for ``init_steps``.\
\n\nParameters\n----------\n"
"deg : input rank-2 array('i') with bounds (f2py_deg_d0,f2py_deg_d1)\n"
"\nReturns\n-------\n"
"steps : rank-2 array('i') with bounds (size(deg, 1),1 + size(deg, 2))";
/* #declfortranroutine# */
static PyObject *f2py_rout_polsys_polystats_init_steps(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int *deg = NULL;
    npy_intp deg_Dims[2] = {-1, -1};
    const int deg_Rank = 2;
    PyArrayObject *capi_deg_tmp = NULL;
    int capi_deg_intent = 0;
    PyObject *deg_capi = Py_None;
    int *steps = NULL;
    npy_intp steps_Dims[2] = {-1, -1};
    const int steps_Rank = 2;
    PyArrayObject *capi_steps_tmp = NULL;
    int capi_steps_intent = 0;
    int f2py_deg_d0 = 0;
    int f2py_deg_d1 = 0;
    static char *capi_kwlist[] = {"deg",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:polsys.polystats.init_steps",\
        capi_kwlist,&deg_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable deg */
    ;
    capi_deg_intent |= F2PY_INTENT_IN;
    capi_deg_tmp = array_from_pyobj(NPY_INT,deg_Dims,deg_Rank,capi_deg_intent,deg_capi);
    if (capi_deg_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting 1st argument `deg' of polsys.polystats.init_steps to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        deg = (int *)(PyArray_DATA(capi_deg_tmp));

    /* Processing variable steps */
    steps_Dims[0]=size(deg, 1),steps_Dims[1]=1 + size(deg, 2);
    capi_steps_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    capi_steps_tmp = array_from_pyobj(NPY_INT,steps_Dims,steps_Rank,capi_steps_intent,Py_None);
    if (capi_steps_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting hidden `steps' of polsys.polystats.init_steps to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        steps = (int *)(PyArray_DATA(capi_steps_tmp));

    /* Processing variable f2py_deg_d0 */
    f2py_deg_d0 = shape(deg, 0);
    /* Processing variable f2py_deg_d1 */
    f2py_deg_d1 = shape(deg, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(deg,steps,&f2py_deg_d0,&f2py_deg_d1);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_steps_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_deg_d1 */
    /* End of cleaning variable f2py_deg_d0 */
    }  /*if (capi_steps_tmp == NULL) ... else of steps*/
    /* End of cleaning variable steps */
    if((PyObject *)capi_deg_tmp!=deg_capi) {
        Py_XDECREF(capi_deg_tmp); }
    }  /*if (capi_deg_tmp == NULL) ... else of deg*/
    /* End of cleaning variable deg */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of init_steps *****************************/

/********************************* init_poly *********************************/
static char doc_f2py_rout_polsys_polsyswrap_init_poly[] = "\
init_poly(n,n_coef_per_eq,all_coef,all_deg)\n\nWrapper for ``init_poly``.\
\n\nParameters\n----------\n"
"n : input int\n"
"n_coef_per_eq : input rank-1 array('i') with bounds (f2py_n_coef_per_eq_d0)\n"
"all_coef : input rank-1 array('D') with bounds (f2py_all_coef_d0)\n"
"all_deg : input rank-2 array('i') with bounds (f2py_all_deg_d0,f2py_all_deg_d1)";
/* #declfortranroutine# */
static PyObject *f2py_rout_polsys_polsyswrap_init_poly(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,complex_double*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int n = 0;
    PyObject *n_capi = Py_None;
    int *n_coef_per_eq = NULL;
    npy_intp n_coef_per_eq_Dims[1] = {-1};
    const int n_coef_per_eq_Rank = 1;
    PyArrayObject *capi_n_coef_per_eq_tmp = NULL;
    int capi_n_coef_per_eq_intent = 0;
    PyObject *n_coef_per_eq_capi = Py_None;
    complex_double *all_coef = NULL;
    npy_intp all_coef_Dims[1] = {-1};
    const int all_coef_Rank = 1;
    PyArrayObject *capi_all_coef_tmp = NULL;
    int capi_all_coef_intent = 0;
    PyObject *all_coef_capi = Py_None;
    int *all_deg = NULL;
    npy_intp all_deg_Dims[2] = {-1, -1};
    const int all_deg_Rank = 2;
    PyArrayObject *capi_all_deg_tmp = NULL;
    int capi_all_deg_intent = 0;
    PyObject *all_deg_capi = Py_None;
    int f2py_n_coef_per_eq_d0 = 0;
    int f2py_all_coef_d0 = 0;
    int f2py_all_deg_d0 = 0;
    int f2py_all_deg_d1 = 0;
    static char *capi_kwlist[] = {"n","n_coef_per_eq","all_coef","all_deg",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:polsys.polsyswrap.init_poly",\
        capi_kwlist,&n_capi,&n_coef_per_eq_capi,&all_coef_capi,&all_deg_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable n */
        f2py_success = int_from_pyobj(&n,n_capi,"polsys.polsyswrap.init_poly() 1st argument (n) can't be converted to int");
    if (f2py_success) {
    /* Processing variable n_coef_per_eq */
    ;
    capi_n_coef_per_eq_intent |= F2PY_INTENT_IN;
    capi_n_coef_per_eq_tmp = array_from_pyobj(NPY_INT,n_coef_per_eq_Dims,n_coef_per_eq_Rank,capi_n_coef_per_eq_intent,n_coef_per_eq_capi);
    if (capi_n_coef_per_eq_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting 2nd argument `n_coef_per_eq' of polsys.polsyswrap.init_poly to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        n_coef_per_eq = (int *)(PyArray_DATA(capi_n_coef_per_eq_tmp));

    /* Processing variable all_coef */
    ;
    capi_all_coef_intent |= F2PY_INTENT_IN;
    capi_all_coef_tmp = array_from_pyobj(NPY_CDOUBLE,all_coef_Dims,all_coef_Rank,capi_all_coef_intent,all_coef_capi);
    if (capi_all_coef_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting 3rd argument `all_coef' of polsys.polsyswrap.init_poly to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        all_coef = (complex_double *)(PyArray_DATA(capi_all_coef_tmp));

    /* Processing variable all_deg */
    ;
    capi_all_deg_intent |= F2PY_INTENT_IN;
    capi_all_deg_tmp = array_from_pyobj(NPY_INT,all_deg_Dims,all_deg_Rank,capi_all_deg_intent,all_deg_capi);
    if (capi_all_deg_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting 4th argument `all_deg' of polsys.polsyswrap.init_poly to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        all_deg = (int *)(PyArray_DATA(capi_all_deg_tmp));

    /* Processing variable f2py_n_coef_per_eq_d0 */
    f2py_n_coef_per_eq_d0 = shape(n_coef_per_eq, 0);
    /* Processing variable f2py_all_coef_d0 */
    f2py_all_coef_d0 = shape(all_coef, 0);
    /* Processing variable f2py_all_deg_d0 */
    f2py_all_deg_d0 = shape(all_deg, 0);
    /* Processing variable f2py_all_deg_d1 */
    f2py_all_deg_d1 = shape(all_deg, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&n,n_coef_per_eq,all_coef,all_deg,&f2py_n_coef_per_eq_d0,&f2py_all_coef_d0,&f2py_all_deg_d0,&f2py_all_deg_d1);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_all_deg_d1 */
    /* End of cleaning variable f2py_all_deg_d0 */
    /* End of cleaning variable f2py_all_coef_d0 */
    /* End of cleaning variable f2py_n_coef_per_eq_d0 */
    if((PyObject *)capi_all_deg_tmp!=all_deg_capi) {
        Py_XDECREF(capi_all_deg_tmp); }
    }  /*if (capi_all_deg_tmp == NULL) ... else of all_deg*/
    /* End of cleaning variable all_deg */
    if((PyObject *)capi_all_coef_tmp!=all_coef_capi) {
        Py_XDECREF(capi_all_coef_tmp); }
    }  /*if (capi_all_coef_tmp == NULL) ... else of all_coef*/
    /* End of cleaning variable all_coef */
    if((PyObject *)capi_n_coef_per_eq_tmp!=n_coef_per_eq_capi) {
        Py_XDECREF(capi_n_coef_per_eq_tmp); }
    }  /*if (capi_n_coef_per_eq_tmp == NULL) ... else of n_coef_per_eq*/
    /* End of cleaning variable n_coef_per_eq */
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of init_poly ******************************/

/******************************* init_partition *******************************/
static char doc_f2py_rout_polsys_polsyswrap_init_partition[] = "\
init_partition(n,num_sets,num_indices,index_bn)\n\nWrapper for ``init_partition``.\
\n\nParameters\n----------\n"
"n : input int\n"
"num_sets : input rank-1 array('i') with bounds (f2py_num_sets_d0)\n"
"num_indices : input rank-2 array('i') with bounds (f2py_num_indices_d0,f2py_num_indices_d1)\n"
"index_bn : input rank-3 array('i') with bounds (f2py_index_bn_d0,f2py_index_bn_d1,f2py_index_bn_d2)";
/* #declfortranroutine# */
static PyObject *f2py_rout_polsys_polsyswrap_init_partition(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int n = 0;
    PyObject *n_capi = Py_None;
    int *num_sets = NULL;
    npy_intp num_sets_Dims[1] = {-1};
    const int num_sets_Rank = 1;
    PyArrayObject *capi_num_sets_tmp = NULL;
    int capi_num_sets_intent = 0;
    PyObject *num_sets_capi = Py_None;
    int *num_indices = NULL;
    npy_intp num_indices_Dims[2] = {-1, -1};
    const int num_indices_Rank = 2;
    PyArrayObject *capi_num_indices_tmp = NULL;
    int capi_num_indices_intent = 0;
    PyObject *num_indices_capi = Py_None;
    int *index_bn = NULL;
    npy_intp index_bn_Dims[3] = {-1, -1, -1};
    const int index_bn_Rank = 3;
    PyArrayObject *capi_index_bn_tmp = NULL;
    int capi_index_bn_intent = 0;
    PyObject *index_bn_capi = Py_None;
    int f2py_num_sets_d0 = 0;
    int f2py_num_indices_d0 = 0;
    int f2py_num_indices_d1 = 0;
    int f2py_index_bn_d0 = 0;
    int f2py_index_bn_d1 = 0;
    int f2py_index_bn_d2 = 0;
    static char *capi_kwlist[] = {"n","num_sets","num_indices","index_bn",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:polsys.polsyswrap.init_partition",\
        capi_kwlist,&n_capi,&num_sets_capi,&num_indices_capi,&index_bn_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable n */
        f2py_success = int_from_pyobj(&n,n_capi,"polsys.polsyswrap.init_partition() 1st argument (n) can't be converted to int");
    if (f2py_success) {
    /* Processing variable num_sets */
    ;
    capi_num_sets_intent |= F2PY_INTENT_IN;
    capi_num_sets_tmp = array_from_pyobj(NPY_INT,num_sets_Dims,num_sets_Rank,capi_num_sets_intent,num_sets_capi);
    if (capi_num_sets_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting 2nd argument `num_sets' of polsys.polsyswrap.init_partition to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        num_sets = (int *)(PyArray_DATA(capi_num_sets_tmp));

    /* Processing variable num_indices */
    ;
    capi_num_indices_intent |= F2PY_INTENT_IN;
    capi_num_indices_tmp = array_from_pyobj(NPY_INT,num_indices_Dims,num_indices_Rank,capi_num_indices_intent,num_indices_capi);
    if (capi_num_indices_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting 3rd argument `num_indices' of polsys.polsyswrap.init_partition to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        num_indices = (int *)(PyArray_DATA(capi_num_indices_tmp));

    /* Processing variable index_bn */
    ;
    capi_index_bn_intent |= F2PY_INTENT_IN;
    capi_index_bn_tmp = array_from_pyobj(NPY_INT,index_bn_Dims,index_bn_Rank,capi_index_bn_intent,index_bn_capi);
    if (capi_index_bn_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting 4th argument `index_bn' of polsys.polsyswrap.init_partition to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        index_bn = (int *)(PyArray_DATA(capi_index_bn_tmp));

    /* Processing variable f2py_num_sets_d0 */
    f2py_num_sets_d0 = shape(num_sets, 0);
    /* Processing variable f2py_num_indices_d0 */
    f2py_num_indices_d0 = shape(num_indices, 0);
    /* Processing variable f2py_num_indices_d1 */
    f2py_num_indices_d1 = shape(num_indices, 1);
    /* Processing variable f2py_index_bn_d0 */
    f2py_index_bn_d0 = shape(index_bn, 0);
    /* Processing variable f2py_index_bn_d1 */
    f2py_index_bn_d1 = shape(index_bn, 1);
    /* Processing variable f2py_index_bn_d2 */
    f2py_index_bn_d2 = shape(index_bn, 2);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&n,num_sets,num_indices,index_bn,&f2py_num_sets_d0,&f2py_num_indices_d0,&f2py_num_indices_d1,&f2py_index_bn_d0,&f2py_index_bn_d1,&f2py_index_bn_d2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_index_bn_d2 */
    /* End of cleaning variable f2py_index_bn_d1 */
    /* End of cleaning variable f2py_index_bn_d0 */
    /* End of cleaning variable f2py_num_indices_d1 */
    /* End of cleaning variable f2py_num_indices_d0 */
    /* End of cleaning variable f2py_num_sets_d0 */
    if((PyObject *)capi_index_bn_tmp!=index_bn_capi) {
        Py_XDECREF(capi_index_bn_tmp); }
    }  /*if (capi_index_bn_tmp == NULL) ... else of index_bn*/
    /* End of cleaning variable index_bn */
    if((PyObject *)capi_num_indices_tmp!=num_indices_capi) {
        Py_XDECREF(capi_num_indices_tmp); }
    }  /*if (capi_num_indices_tmp == NULL) ... else of num_indices*/
    /* End of cleaning variable num_indices */
    if((PyObject *)capi_num_sets_tmp!=num_sets_capi) {
        Py_XDECREF(capi_num_sets_tmp); }
    }  /*if (capi_num_sets_tmp == NULL) ... else of num_sets*/
    /* End of cleaning variable num_sets */
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of init_partition ***************************/

/********************************* show_coef *********************************/
static char doc_f2py_rout_polsys_polsyswrap_show_coef[] = "\
show_coef([homo])\n\nWrapper for ``show_coef``.\
\n\nOther Parameters\n----------------\n"
"homo : input int";
/*  */
static PyObject *f2py_rout_polsys_polsyswrap_show_coef(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int homo = 0;
    PyObject *homo_capi = Py_None;
    static char *capi_kwlist[] = {"homo",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|O:polsys.polsyswrap.show_coef",\
        capi_kwlist,&homo_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable homo */
    if (homo_capi != Py_None)
        homo = (int)PyObject_IsTrue(homo_capi);
        f2py_success = 1;
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&homo);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of homo*/
    /* End of cleaning variable homo */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of show_coef ******************************/

/******************************* show_partition *******************************/
static char doc_f2py_rout_polsys_polsyswrap_show_partition[] = "\
show_partition()\n\nWrapper for ``show_partition``.\
\n";
/*  */
static PyObject *f2py_rout_polsys_polsyswrap_show_partition(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:polsys.polsyswrap.show_partition",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of show_partition ***************************/

/*********************************** solve ***********************************/
static char doc_f2py_rout_polsys_polsyswrap_solve[] = "\
bplp = solve(tracktol,finaltol,singtol,[dense])\n\nWrapper for ``solve``.\
\n\nParameters\n----------\n"
"tracktol : input float\n"
"finaltol : input float\n"
"singtol : in/output rank-0 array(float,'d')\n"
"\nOther Parameters\n----------------\n"
"dense : input int\n"
"\nReturns\n-------\n"
"bplp : int";
/*  */
static PyObject *f2py_rout_polsys_polsyswrap_solve(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double tracktol = 0;
    PyObject *tracktol_capi = Py_None;
    double finaltol = 0;
    PyObject *finaltol_capi = Py_None;
    double singtol = 0;
    PyObject *singtol_capi = Py_None;
    int dense = 0;
    PyObject *dense_capi = Py_None;
    int bplp = 0;
    static char *capi_kwlist[] = {"tracktol","finaltol","singtol","dense",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:polsys.polsyswrap.solve",\
        capi_kwlist,&tracktol_capi,&finaltol_capi,&singtol_capi,&dense_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable tracktol */
        f2py_success = double_from_pyobj(&tracktol,tracktol_capi,"polsys.polsyswrap.solve() 1st argument (tracktol) can't be converted to double");
    if (f2py_success) {
    /* Processing variable finaltol */
        f2py_success = double_from_pyobj(&finaltol,finaltol_capi,"polsys.polsyswrap.solve() 2nd argument (finaltol) can't be converted to double");
    if (f2py_success) {
    /* Processing variable singtol */
        f2py_success = double_from_pyobj(&singtol,singtol_capi,"polsys.polsyswrap.solve() 3rd argument (singtol) can't be converted to double");
    if (f2py_success) {
    /* Processing variable dense */
    if (dense_capi != Py_None)
        dense = (int)PyObject_IsTrue(dense_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable bplp */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&tracktol,&finaltol,&singtol,&dense,&bplp);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
    f2py_success = try_pyarr_from_double(singtol_capi,&singtol);
    if (f2py_success) {
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",bplp);
/*closepyobjfrom*/
    } /*if (f2py_success) of singtol pyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable bplp */
    } /*if (f2py_success) of dense*/
    /* End of cleaning variable dense */
    } /*if (f2py_success) of singtol*/
    /* End of cleaning variable singtol */
    } /*if (f2py_success) of finaltol*/
    /* End of cleaning variable finaltol */
    } /*if (f2py_success) of tracktol*/
    /* End of cleaning variable tracktol */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of solve ********************************/

/*********************************** refine ***********************************/
static char doc_f2py_rout_polsys_polsyswrap_refine[] = "\
refine(path,tracktol,finaltol,singtol,[dense,k])\n\nWrapper for ``refine``.\
\n\nParameters\n----------\n"
"path : input rank-1 array('i') with bounds (k)\n"
"tracktol : input float\n"
"finaltol : input float\n"
"singtol : in/output rank-0 array(float,'d')\n"
"\nOther Parameters\n----------------\n"
"dense : input int\n"
"k : input int, optional\n    Default: len(path)";
/*  */
static PyObject *f2py_rout_polsys_polsyswrap_refine(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int *path = NULL;
    npy_intp path_Dims[1] = {-1};
    const int path_Rank = 1;
    PyArrayObject *capi_path_tmp = NULL;
    int capi_path_intent = 0;
    PyObject *path_capi = Py_None;
    double tracktol = 0;
    PyObject *tracktol_capi = Py_None;
    double finaltol = 0;
    PyObject *finaltol_capi = Py_None;
    double singtol = 0;
    PyObject *singtol_capi = Py_None;
    int dense = 0;
    PyObject *dense_capi = Py_None;
    int k = 0;
    PyObject *k_capi = Py_None;
    static char *capi_kwlist[] = {"path","tracktol","finaltol","singtol","dense","k",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|OO:polsys.polsyswrap.refine",\
        capi_kwlist,&path_capi,&tracktol_capi,&finaltol_capi,&singtol_capi,&dense_capi,&k_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable path */
    ;
    capi_path_intent |= F2PY_INTENT_IN;
    capi_path_tmp = array_from_pyobj(NPY_INT,path_Dims,path_Rank,capi_path_intent,path_capi);
    if (capi_path_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : polsys_error,"failed in converting 1st argument `path' of polsys.polsyswrap.refine to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        path = (int *)(PyArray_DATA(capi_path_tmp));

    /* Processing variable tracktol */
        f2py_success = double_from_pyobj(&tracktol,tracktol_capi,"polsys.polsyswrap.refine() 2nd argument (tracktol) can't be converted to double");
    if (f2py_success) {
    /* Processing variable finaltol */
        f2py_success = double_from_pyobj(&finaltol,finaltol_capi,"polsys.polsyswrap.refine() 3rd argument (finaltol) can't be converted to double");
    if (f2py_success) {
    /* Processing variable singtol */
        f2py_success = double_from_pyobj(&singtol,singtol_capi,"polsys.polsyswrap.refine() 4th argument (singtol) can't be converted to double");
    if (f2py_success) {
    /* Processing variable dense */
    if (dense_capi != Py_None)
        dense = (int)PyObject_IsTrue(dense_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable k */
    if (k_capi == Py_None) k = len(path); else
        f2py_success = int_from_pyobj(&k,k_capi,"polsys.polsyswrap.refine() 2nd keyword (k) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(len(path)>=k,"len(path)>=k","2nd keyword k","refine:k=%d",k) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(path,&tracktol,&finaltol,&singtol,&dense,&k);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
    f2py_success = try_pyarr_from_double(singtol_capi,&singtol);
    if (f2py_success) {
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
    } /*if (f2py_success) of singtol pyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(len(path)>=k)*/
    } /*if (f2py_success) of k*/
    /* End of cleaning variable k */
    } /*if (f2py_success) of dense*/
    /* End of cleaning variable dense */
    } /*if (f2py_success) of singtol*/
    /* End of cleaning variable singtol */
    } /*if (f2py_success) of finaltol*/
    /* End of cleaning variable finaltol */
    } /*if (f2py_success) of tracktol*/
    /* End of cleaning variable tracktol */
    if((PyObject *)capi_path_tmp!=path_capi) {
        Py_XDECREF(capi_path_tmp); }
    }  /*if (capi_path_tmp == NULL) ... else of path*/
    /* End of cleaning variable path */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of refine *******************************/

/*********************************** bezout ***********************************/
static char doc_f2py_rout_polsys_polsyswrap_bezout[] = "\
bplp = bezout(singtol)\n\nWrapper for ``bezout``.\
\n\nParameters\n----------\n"
"singtol : in/output rank-0 array(float,'d')\n"
"\nReturns\n-------\n"
"bplp : int";
/*  */
static PyObject *f2py_rout_polsys_polsyswrap_bezout(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double singtol = 0;
    PyObject *singtol_capi = Py_None;
    int bplp = 0;
    static char *capi_kwlist[] = {"singtol",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:polsys.polsyswrap.bezout",\
        capi_kwlist,&singtol_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable singtol */
        f2py_success = double_from_pyobj(&singtol,singtol_capi,"polsys.polsyswrap.bezout() 1st argument (singtol) can't be converted to double");
    if (f2py_success) {
    /* Processing variable bplp */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&singtol,&bplp);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
    f2py_success = try_pyarr_from_double(singtol_capi,&singtol);
    if (f2py_success) {
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",bplp);
/*closepyobjfrom*/
    } /*if (f2py_success) of singtol pyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable bplp */
    } /*if (f2py_success) of singtol*/
    /* End of cleaning variable singtol */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of bezout *******************************/

/*********************************** report ***********************************/
static char doc_f2py_rout_polsys_polsyswrap_report[] = "\
status = report()\n\nWrapper for ``report``.\
\n\nReturns\n-------\n"
"status : int";
/*  */
static PyObject *f2py_rout_polsys_polsyswrap_report(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int status = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:polsys.polsyswrap.report",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable status */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&status);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",status);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable status */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of report *******************************/

/******************************** cleanup_pol ********************************/
static char doc_f2py_rout_polsys_polsyswrap_cleanup_pol[] = "\
cleanup_pol()\n\nWrapper for ``cleanup_pol``.\
\n";
/*  */
static PyObject *f2py_rout_polsys_polsyswrap_cleanup_pol(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:polsys.polsyswrap.cleanup_pol",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of cleanup_pol *****************************/

/******************************** cleanup_par ********************************/
static char doc_f2py_rout_polsys_polsyswrap_cleanup_par[] = "\
cleanup_par()\n\nWrapper for ``cleanup_par``.\
\n";
/*  */
static PyObject *f2py_rout_polsys_polsyswrap_cleanup_par(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:polsys.polsyswrap.cleanup_par",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of cleanup_par *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_polystats_def[] = {
  {"vdmax",2,{{-1,-1}},NPY_INT},
  {"coefsteps",2,{{-1,-1}},NPY_INT},
  {"init_steps",-1,{{-1}},0,NULL,(void *)f2py_rout_polsys_polystats_init_steps,doc_f2py_rout_polsys_polystats_init_steps},
  {NULL}
};

static void f2py_setup_polystats(void (*vdmax)(int*,int*,void(*)(char*,int*),int*),void (*coefsteps)(int*,int*,void(*)(char*,int*),int*),char *init_steps) {
  int i_f2py=0;
  f2py_polystats_def[i_f2py++].func = vdmax;
  f2py_polystats_def[i_f2py++].func = coefsteps;
  f2py_polystats_def[i_f2py++].data = init_steps;
}
extern void F_FUNC(f2pyinitpolystats,F2PYINITPOLYSTATS)(void (*)(void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),char *));
static void f2py_init_polystats(void) {
  F_FUNC(f2pyinitpolystats,F2PYINITPOLYSTATS)(f2py_setup_polystats);
}


static FortranDataDef f2py_polsyswrap_def[] = {
  {"variables_scale_factors",1,{{-1}},NPY_DOUBLE},
  {"solve_status",0,{{-1}},NPY_INT},
  {"myroots",2,{{-1,-1}},NPY_CDOUBLE},
  {"path_status",1,{{-1}},NPY_INT},
  {"num_jac_eval",1,{{-1}},NPY_INT},
  {"init_poly",-1,{{-1}},0,NULL,(void *)f2py_rout_polsys_polsyswrap_init_poly,doc_f2py_rout_polsys_polsyswrap_init_poly},
  {"init_partition",-1,{{-1}},0,NULL,(void *)f2py_rout_polsys_polsyswrap_init_partition,doc_f2py_rout_polsys_polsyswrap_init_partition},
  {"show_coef",-1,{{-1}},0,NULL,(void *)f2py_rout_polsys_polsyswrap_show_coef,doc_f2py_rout_polsys_polsyswrap_show_coef},
  {"show_partition",-1,{{-1}},0,NULL,(void *)f2py_rout_polsys_polsyswrap_show_partition,doc_f2py_rout_polsys_polsyswrap_show_partition},
  {"solve",-1,{{-1}},0,NULL,(void *)f2py_rout_polsys_polsyswrap_solve,doc_f2py_rout_polsys_polsyswrap_solve},
  {"refine",-1,{{-1}},0,NULL,(void *)f2py_rout_polsys_polsyswrap_refine,doc_f2py_rout_polsys_polsyswrap_refine},
  {"bezout",-1,{{-1}},0,NULL,(void *)f2py_rout_polsys_polsyswrap_bezout,doc_f2py_rout_polsys_polsyswrap_bezout},
  {"report",-1,{{-1}},0,NULL,(void *)f2py_rout_polsys_polsyswrap_report,doc_f2py_rout_polsys_polsyswrap_report},
  {"cleanup_pol",-1,{{-1}},0,NULL,(void *)f2py_rout_polsys_polsyswrap_cleanup_pol,doc_f2py_rout_polsys_polsyswrap_cleanup_pol},
  {"cleanup_par",-1,{{-1}},0,NULL,(void *)f2py_rout_polsys_polsyswrap_cleanup_par,doc_f2py_rout_polsys_polsyswrap_cleanup_par},
  {NULL}
};

static void f2py_setup_polsyswrap(void (*variables_scale_factors)(int*,int*,void(*)(char*,int*),int*),char *solve_status,void (*myroots)(int*,int*,void(*)(char*,int*),int*),void (*path_status)(int*,int*,void(*)(char*,int*),int*),void (*num_jac_eval)(int*,int*,void(*)(char*,int*),int*),char *init_poly,char *init_partition,char *show_coef,char *show_partition,char *solve,char *refine,char *bezout,char *report,char *cleanup_pol,char *cleanup_par) {
  int i_f2py=0;
  f2py_polsyswrap_def[i_f2py++].func = variables_scale_factors;
  f2py_polsyswrap_def[i_f2py++].data = solve_status;
  f2py_polsyswrap_def[i_f2py++].func = myroots;
  f2py_polsyswrap_def[i_f2py++].func = path_status;
  f2py_polsyswrap_def[i_f2py++].func = num_jac_eval;
  f2py_polsyswrap_def[i_f2py++].data = init_poly;
  f2py_polsyswrap_def[i_f2py++].data = init_partition;
  f2py_polsyswrap_def[i_f2py++].data = show_coef;
  f2py_polsyswrap_def[i_f2py++].data = show_partition;
  f2py_polsyswrap_def[i_f2py++].data = solve;
  f2py_polsyswrap_def[i_f2py++].data = refine;
  f2py_polsyswrap_def[i_f2py++].data = bezout;
  f2py_polsyswrap_def[i_f2py++].data = report;
  f2py_polsyswrap_def[i_f2py++].data = cleanup_pol;
  f2py_polsyswrap_def[i_f2py++].data = cleanup_par;
}
extern void F_FUNC(f2pyinitpolsyswrap,F2PYINITPOLSYSWRAP)(void (*)(void (*)(int*,int*,void(*)(char*,int*),int*),char*,void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),char *,char *,char *,char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_polsyswrap(void) {
  F_FUNC(f2pyinitpolsyswrap,F2PYINITPOLSYSWRAP)(f2py_setup_polsyswrap);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"dhorner_mv",-1,{{-1}},0,(char *)F_FUNC_US(dhorner_mv,DHORNER_MV),(f2py_init_func)f2py_rout_polsys_dhorner_mv,doc_f2py_rout_polsys_dhorner_mv},
    {"target_system_user",-1,{{-1}},0,(char *)F_FUNC_US(target_system_user,TARGET_SYSTEM_USER),(f2py_init_func)f2py_rout_polsys_target_system_user,doc_f2py_rout_polsys_target_system_user},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "polsys",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_polsys(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = polsys_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module polsys (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.23.1");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'polsys' is auto-generated with f2py (version:1.23.1).\nFunctions:\n"
"    p,dp = dhorner_mv(eq,ncoef,x0,nv=len(x0))\n"
"    f,df = target_system_user(proj_coef,xc,n=(len(proj_coef)-1))\n"
"Fortran 90/95 modules:\n""  polystats --- vdmax,coefsteps,init_steps()""  polsyswrap --- variables_scale_factors,solve_status,myroots,path_status,num_jac_eval,init_poly(),init_partition(),show_coef(),show_partition(),solve(),refine(),bezout(),report(),cleanup_pol(),cleanup_par()"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.23.1");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    polsys_error = PyErr_NewException ("polsys.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_polsys_error", polsys_error);
    Py_DECREF(polsys_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }













/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "polsyswrap", PyFortranObject_New(f2py_polsyswrap_def,f2py_init_polsyswrap));
  PyDict_SetItemString(d, "polystats", PyFortranObject_New(f2py_polystats_def,f2py_init_polystats));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"polsys");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
