!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.23.1)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2py_polystats_getdims_vdmax(r,s,f2pysetdata,flag)
      use polystats, only: d => vdmax

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_polystats_getdims_vdmax
      subroutine f2py_polystats_getdims_coefsteps(r,s,f2pysetdata,flag)
      use polystats, only: d => coefsteps

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_polystats_getdims_coefsteps
      subroutine f2pywrap_polystats_init_steps (deg, steps, f2py_deg_d0,&
     & f2py_deg_d1)
      use polystats, only : init_steps
      integer f2py_deg_d0
      integer f2py_deg_d1
      integer deg(f2py_deg_d0,f2py_deg_d1)
      integer steps(size(deg, 1),1 + size(deg, 2))
      call init_steps(deg, steps)
      end subroutine f2pywrap_polystats_init_steps
      
      subroutine f2pyinitpolystats(f2pysetupfunc)
      use polystats, only : vdmax
      use polystats, only : coefsteps
      interface 
      subroutine f2pywrap_polystats_init_steps (deg, steps, f2py_deg_d0,&
     & f2py_deg_d1)
      integer f2py_deg_d0
      integer f2py_deg_d1
      integer deg(f2py_deg_d0,f2py_deg_d1)
      integer steps(size(deg, 1),1 + size(deg, 2))
      end subroutine f2pywrap_polystats_init_steps
      end interface
      external f2pysetupfunc
      external f2py_polystats_getdims_vdmax
      external f2py_polystats_getdims_coefsteps
      call f2pysetupfunc(f2py_polystats_getdims_vdmax,f2py_polystats_get&
     &dims_coefsteps,f2pywrap_polystats_init_steps)
      end subroutine f2pyinitpolystats

      subroutine f2py_polsyswrap_getdims_variables_scale_factors(r,s,f2p&
     &ysetdata,flag)
      use polsyswrap, only: d => variables_scale_factors

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_polsyswrap_getdims_variables_scale_factors
      subroutine f2py_polsyswrap_getdims_myroots(r,s,f2pysetdata,flag)
      use polsyswrap, only: d => myroots

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_polsyswrap_getdims_myroots
      subroutine f2py_polsyswrap_getdims_path_status(r,s,f2pysetdata,fla&
     &g)
      use polsyswrap, only: d => path_status

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_polsyswrap_getdims_path_status
      subroutine f2py_polsyswrap_getdims_num_jac_eval(r,s,f2pysetdata,fl&
     &ag)
      use polsyswrap, only: d => num_jac_eval

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_polsyswrap_getdims_num_jac_eval
      subroutine f2pywrap_polsyswrap_init_poly (n, n_coef_per_eq, all_co&
     &ef, all_deg, f2py_n_coef_per_eq_d0, f2py_all_coef_d0, f2py_all_deg&
     &_d0, f2py_all_deg_d1)
      use polsyswrap, only : init_poly
      integer n
      integer f2py_n_coef_per_eq_d0
      integer f2py_all_coef_d0
      integer f2py_all_deg_d0
      integer f2py_all_deg_d1
      integer n_coef_per_eq(f2py_n_coef_per_eq_d0)
      complex(kind=8) all_coef(f2py_all_coef_d0)
      integer all_deg(f2py_all_deg_d0,f2py_all_deg_d1)
      call init_poly(n, n_coef_per_eq, all_coef, all_deg)
      end subroutine f2pywrap_polsyswrap_init_poly
      subroutine f2pywrap_polsyswrap_init_partition (n, num_sets, num_in&
     &dices, index_bn, f2py_num_sets_d0, f2py_num_indices_d0, f2py_num_i&
     &ndices_d1, f2py_index_bn_d0, f2py_index_bn_d1, f2py_index_bn_d2)
      use polsyswrap, only : init_partition
      integer n
      integer f2py_num_sets_d0
      integer f2py_num_indices_d0
      integer f2py_num_indices_d1
      integer f2py_index_bn_d0
      integer f2py_index_bn_d1
      integer f2py_index_bn_d2
      integer num_sets(f2py_num_sets_d0)
      integer num_indices(f2py_num_indices_d0,f2py_num_indices_d1)
      integer index_bn(f2py_index_bn_d0,f2py_index_bn_d1,f2py_index_bn_d&
     &2)
      call init_partition(n, num_sets, num_indices, index_bn)
      end subroutine f2pywrap_polsyswrap_init_partition
      
      subroutine f2pyinitpolsyswrap(f2pysetupfunc)
      use polsyswrap, only : variables_scale_factors
      use polsyswrap, only : solve_status
      use polsyswrap, only : myroots
      use polsyswrap, only : path_status
      use polsyswrap, only : num_jac_eval
      use polsyswrap, only : show_coef
      use polsyswrap, only : show_partition
      use polsyswrap, only : solve
      use polsyswrap, only : refine
      use polsyswrap, only : bezout
      use polsyswrap, only : report
      use polsyswrap, only : cleanup_pol
      use polsyswrap, only : cleanup_par
      interface 
      subroutine f2pywrap_polsyswrap_init_poly (n, n_coef_per_eq, all_co&
     &ef, all_deg, f2py_n_coef_per_eq_d0, f2py_all_coef_d0, f2py_all_deg&
     &_d0, f2py_all_deg_d1)
      integer n
      integer f2py_n_coef_per_eq_d0
      integer f2py_all_coef_d0
      integer f2py_all_deg_d0
      integer f2py_all_deg_d1
      integer n_coef_per_eq(f2py_n_coef_per_eq_d0)
      complex(kind=8) all_coef(f2py_all_coef_d0)
      integer all_deg(f2py_all_deg_d0,f2py_all_deg_d1)
      end subroutine f2pywrap_polsyswrap_init_poly 
      subroutine f2pywrap_polsyswrap_init_partition (n, num_sets, num_in&
     &dices, index_bn, f2py_num_sets_d0, f2py_num_indices_d0, f2py_num_i&
     &ndices_d1, f2py_index_bn_d0, f2py_index_bn_d1, f2py_index_bn_d2)
      integer n
      integer f2py_num_sets_d0
      integer f2py_num_indices_d0
      integer f2py_num_indices_d1
      integer f2py_index_bn_d0
      integer f2py_index_bn_d1
      integer f2py_index_bn_d2
      integer num_sets(f2py_num_sets_d0)
      integer num_indices(f2py_num_indices_d0,f2py_num_indices_d1)
      integer index_bn(f2py_index_bn_d0,f2py_index_bn_d1,f2py_index_bn_d&
     &2)
      end subroutine f2pywrap_polsyswrap_init_partition
      end interface
      external f2pysetupfunc
      external f2py_polsyswrap_getdims_variables_scale_factors
      external f2py_polsyswrap_getdims_myroots
      external f2py_polsyswrap_getdims_path_status
      external f2py_polsyswrap_getdims_num_jac_eval
      call f2pysetupfunc(f2py_polsyswrap_getdims_variables_scale_factors&
     &,solve_status,f2py_polsyswrap_getdims_myroots,f2py_polsyswrap_getd&
     &ims_path_status,f2py_polsyswrap_getdims_num_jac_eval,f2pywrap_pols&
     &yswrap_init_poly,f2pywrap_polsyswrap_init_partition,show_coef,show&
     &_partition,solve,refine,bezout,report,cleanup_pol,cleanup_par)
      end subroutine f2pyinitpolsyswrap


