# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.0.4.dev27+gf52c3f4.d20230303'
__version_tuple__ = version_tuple = (1, 0, 4, 'dev27', 'gf52c3f4.d20230303')
