
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-06T09:19:13+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec6f3ba74d2120609bb2597a15c6eb625fb93fd9",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
