
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-06T07:10:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "06cd06a1caa9de501e4616bcc4f4928b2ff0350c",
 "version": "1.18.2.post0.dev179"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
