# Generated by Django 3.2 on 2022-11-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0004_auto_20200722_1231'),
        ('dubletten_tool', '0007_group_vorfin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='vorfin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_group', to='apis_entities.person'),
        ),
    ]
