
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-06T16:52:45-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d0bc6977b6b3c7bc04e60439a08ba0290513f73",
 "version": "1.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
