# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ..configuration import Configuration


class FileUpdate(object):
    """
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'attributes': 'dict(str, object)',
        'description': 'str',
        'name': 'str',
        'path': 'str'
    }

    attribute_map = {
        'attributes': 'attributes',
        'description': 'description',
        'name': 'name',
        'path': 'path'
    }

    def __init__(self, attributes=None, description=None, name=None, path=None, local_vars_configuration=None):  # noqa: E501
        """FileUpdate - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._attributes = None
        self._description = None
        self._name = None
        self._path = None
        self.discriminator = None

        if attributes is not None:
            self.attributes = attributes
        if description is not None:
            self.description = description
        if name is not None:
            self.name = name
        if path is not None:
            self.path = path

    @property
    def attributes(self):
        """
        Object containing attribute values

        :return: The attributes of this FileUpdate. 
        :rtype: dict(str, object)
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """
        Object containing attribute values

        :param attributes: The attributes of this FileUpdate.
        :type: dict(str, object)
        """

        self._attributes = attributes

    @property
    def description(self):
        """
        Description of file

        :return: The description of this FileUpdate. 
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Description of file

        :param description: The description of this FileUpdate.
        :type: str
        """

        self._description = description

    @property
    def name(self):
        """
        Name of file

        :return: The name of this FileUpdate. 
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Name of file

        :param name: The name of this FileUpdate.
        :type: str
        """

        self._name = name

    @property
    def path(self):
        """
        Relative URL to the file

        :return: The path of this FileUpdate. 
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """
        Relative URL to the file

        :param path: The path of this FileUpdate.
        :type: str
        """

        self._path = path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileUpdate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FileUpdate):
            return True

        return self.to_dict() != other.to_dict()
