# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_existential = {
    'am looking for the': 3,
 'am trying to find': 3,
 'can i': 3,
 'can i find the': 3,
 'can i get to': 3,
 'can i still': 3,
 'can you give me': 3,
 'can you help me': 6,
 'can you inform me': 3,
 'can you point me': 3,
 'can you tell me': 12,
 'could give me some': 6,
 'do i': 6,
 'do i send': 3,
 'do we do when': 3,
 'do you suggest i': 3,
 'else can i do': 3,
 'give me directions to': 3,
 'give me some directions': 6,
 'go to find the': 3,
 'help me find the': 3,
 'help me locate the': 3,
 'how can i': 3,
 'how can i do': 3,
 'how can i get': 3,
 'how do i': 3,
 'how do i find': 3,
 'how do you do': 3,
 'how do you suggest': 3,
 'how else can i': 3,
 'how is': 3,
 'how long': 3,
 'how long will it': 3,
 'how many': 3,
 'how might i': 3,
 'how might i go': 3,
 'how much': 3,
 'how much is': 3,
 'how much money': 3,
 'how much money is': 3,
 'how to get to': 3,
 'i am looking for': 3,
 'i am trying to': 3,
 'i can find the': 3,
 'i get to the': 3,
 'i need to find': 3,
 'i would like it': 3,
 "i'd like it if": 3,
 'if you could give': 6,
 'inform me where i': 3,
 'is it possible': 3,
 'is it possible to': 3,
 'is the date': 3,
 'is the due date': 3,
 'is there a': 3,
 'is there an': 3,
 'it if you could': 6,
 'like it if you': 6,
 'long will it take': 3,
 'me directions to the': 3,
 'me how to get': 3,
 'me some directions to': 6,
 'me the way to': 3,
 'me where i can': 3,
 'me where to go': 3,
 'might i go about': 3,
 'need to find the': 3,
 'point me towards the': 3,
 'some directions to the': 6,
 'tell me how to': 3,
 'tell me the way': 3,
 'tell me where the': 3,
 'tell me where to': 3,
 'the way to the': 3,
 'to get to the': 3,
 'to go to find': 3,
 'trying to find the': 3,
 'what do we do': 3,
 'what does': 3,
 'what happens if': 3,
 'what is': 3,
 'what is a': 3,
 'what is an': 3,
 'what is the': 3,
 'when is the': 3,
 'when is the due': 3,
 'where are': 3,
 'where can i find': 3,
 'where do': 3,
 'where do i': 3,
 'where i can find': 3,
 'where is': 3,
 'where is the': 3,
 'where to go to': 3,
 'who do': 3,
 'would like it if': 3,
 'you could give me': 6,
 'you give me directions': 3,
 'you help me find': 3,
 'you help me locate': 3,
 'you inform me where': 3,
 'you point me towards': 3,
 'you tell me how': 3,
 'you tell me the': 3,
 'you tell me where': 6
}
