# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_how_long_time = {
    'am looking for the': 4,
 'am trying to find': 4,
 'can i': 4,
 'can i find the': 4,
 'can i get to': 4,
 'can i still': 4,
 'can you give me': 4,
 'can you help me': 8,
 'can you inform me': 4,
 'can you point me': 4,
 'can you tell me': 16,
 'could give me some': 8,
 'do i': 8,
 'do i send': 4,
 'do we do when': 4,
 'do you suggest i': 4,
 'else can i do': 4,
 'give me directions to': 4,
 'give me some directions': 8,
 'go to find the': 4,
 'help me find the': 4,
 'help me locate the': 4,
 'how can i': 4,
 'how can i do': 4,
 'how can i get': 4,
 'how do i': 4,
 'how do i find': 4,
 'how do you do': 4,
 'how do you suggest': 4,
 'how else can i': 4,
 'how is': 4,
 'how long': 4,
 'how long will it': 4,
 'how many': 4,
 'how might i': 4,
 'how might i go': 4,
 'how much': 4,
 'how much is': 4,
 'how much money': 4,
 'how much money is': 4,
 'how to get to': 4,
 'i am looking for': 4,
 'i am trying to': 4,
 'i can find the': 4,
 'i get to the': 4,
 'i need to find': 4,
 'i would like it': 4,
 "i'd like it if": 4,
 'if you could give': 8,
 'inform me where i': 4,
 'is it possible': 4,
 'is it possible to': 4,
 'is the date': 4,
 'is the due date': 4,
 'is there a': 4,
 'is there an': 4,
 'it if you could': 8,
 'like it if you': 8,
 'long will it take': 4,
 'me directions to the': 4,
 'me how to get': 4,
 'me some directions to': 8,
 'me the way to': 4,
 'me where i can': 4,
 'me where to go': 4,
 'might i go about': 4,
 'need to find the': 4,
 'point me towards the': 4,
 'some directions to the': 8,
 'tell me how to': 4,
 'tell me the way': 4,
 'tell me where the': 4,
 'tell me where to': 4,
 'the way to the': 4,
 'to get to the': 4,
 'to go to find': 4,
 'trying to find the': 4,
 'what do we do': 4,
 'what does': 4,
 'what happens if': 4,
 'what is': 4,
 'what is a': 4,
 'what is an': 4,
 'what is the': 4,
 'when is the': 4,
 'when is the due': 4,
 'where are': 4,
 'where can i find': 4,
 'where do': 4,
 'where do i': 4,
 'where i can find': 4,
 'where is': 4,
 'where is the': 4,
 'where to go to': 4,
 'who do': 4,
 'would like it if': 4,
 'you could give me': 8,
 'you give me directions': 4,
 'you help me find': 4,
 'you help me locate': 4,
 'you inform me where': 4,
 'you point me towards': 4,
 'you tell me how': 4,
 'you tell me the': 4,
 'you tell me where': 8
}
