# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_when_date = {
    'am looking for the': 10,
 'am trying to find': 10,
 'can i': 10,
 'can i find the': 10,
 'can i get to': 10,
 'can i still': 10,
 'can you give me': 10,
 'can you help me': 20,
 'can you inform me': 10,
 'can you point me': 10,
 'can you tell me': 40,
 'could give me some': 20,
 'do i': 20,
 'do i send': 10,
 'do we do when': 10,
 'do you suggest i': 10,
 'else can i do': 10,
 'give me directions to': 10,
 'give me some directions': 20,
 'go to find the': 10,
 'help me find the': 10,
 'help me locate the': 10,
 'how can i': 10,
 'how can i do': 10,
 'how can i get': 10,
 'how do i': 10,
 'how do i find': 10,
 'how do you do': 10,
 'how do you suggest': 10,
 'how else can i': 10,
 'how is': 10,
 'how long': 10,
 'how long will it': 10,
 'how many': 10,
 'how might i': 10,
 'how might i go': 10,
 'how much': 10,
 'how much is': 10,
 'how much money': 10,
 'how much money is': 10,
 'how to get to': 10,
 'i am looking for': 10,
 'i am trying to': 10,
 'i can find the': 10,
 'i get to the': 10,
 'i need to find': 10,
 'i would like it': 10,
 "i'd like it if": 10,
 'if you could give': 20,
 'inform me where i': 10,
 'is it possible': 10,
 'is it possible to': 10,
 'is the date': 10,
 'is the due date': 10,
 'is there a': 10,
 'is there an': 10,
 'it if you could': 20,
 'like it if you': 20,
 'long will it take': 10,
 'me directions to the': 10,
 'me how to get': 10,
 'me some directions to': 20,
 'me the way to': 10,
 'me where i can': 10,
 'me where to go': 10,
 'might i go about': 10,
 'need to find the': 10,
 'point me towards the': 10,
 'some directions to the': 20,
 'tell me how to': 10,
 'tell me the way': 10,
 'tell me where the': 10,
 'tell me where to': 10,
 'the way to the': 10,
 'to get to the': 10,
 'to go to find': 10,
 'trying to find the': 10,
 'what do we do': 10,
 'what does': 10,
 'what happens if': 10,
 'what is': 10,
 'what is a': 10,
 'what is an': 10,
 'what is the': 10,
 'when is the': 10,
 'when is the due': 10,
 'where are': 10,
 'where can i find': 10,
 'where do': 10,
 'where do i': 10,
 'where i can find': 10,
 'where is': 10,
 'where is the': 10,
 'where to go to': 10,
 'who do': 10,
 'would like it if': 10,
 'you could give me': 20,
 'you give me directions': 10,
 'you help me find': 10,
 'you help me locate': 10,
 'you inform me where': 10,
 'you point me towards': 10,
 'you tell me how': 10,
 'you tell me the': 10,
 'you tell me where': 20
}
