# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_where_location = {
    'am looking for the': 12,
 'am trying to find': 12,
 'can i': 12,
 'can i find the': 12,
 'can i get to': 12,
 'can i still': 12,
 'can you give me': 12,
 'can you help me': 24,
 'can you inform me': 12,
 'can you point me': 12,
 'can you tell me': 48,
 'could give me some': 24,
 'do i': 24,
 'do i send': 12,
 'do we do when': 12,
 'do you suggest i': 12,
 'else can i do': 12,
 'give me directions to': 12,
 'give me some directions': 24,
 'go to find the': 12,
 'help me find the': 12,
 'help me locate the': 12,
 'how can i': 12,
 'how can i do': 12,
 'how can i get': 12,
 'how do i': 12,
 'how do i find': 12,
 'how do you do': 12,
 'how do you suggest': 12,
 'how else can i': 12,
 'how is': 12,
 'how long': 12,
 'how long will it': 12,
 'how many': 12,
 'how might i': 12,
 'how might i go': 12,
 'how much': 12,
 'how much is': 12,
 'how much money': 12,
 'how much money is': 12,
 'how to get to': 12,
 'i am looking for': 12,
 'i am trying to': 12,
 'i can find the': 12,
 'i get to the': 12,
 'i need to find': 12,
 'i would like it': 12,
 "i'd like it if": 12,
 'if you could give': 24,
 'inform me where i': 12,
 'is it possible': 12,
 'is it possible to': 12,
 'is the date': 12,
 'is the due date': 12,
 'is there a': 12,
 'is there an': 12,
 'it if you could': 24,
 'like it if you': 24,
 'long will it take': 12,
 'me directions to the': 12,
 'me how to get': 12,
 'me some directions to': 24,
 'me the way to': 12,
 'me where i can': 12,
 'me where to go': 12,
 'might i go about': 12,
 'need to find the': 12,
 'point me towards the': 12,
 'some directions to the': 24,
 'tell me how to': 12,
 'tell me the way': 12,
 'tell me where the': 12,
 'tell me where to': 12,
 'the way to the': 12,
 'to get to the': 12,
 'to go to find': 12,
 'trying to find the': 12,
 'what do we do': 12,
 'what does': 12,
 'what happens if': 12,
 'what is': 12,
 'what is a': 12,
 'what is an': 12,
 'what is the': 12,
 'when is the': 12,
 'when is the due': 12,
 'where are': 12,
 'where can i find': 12,
 'where do': 12,
 'where do i': 12,
 'where i can find': 12,
 'where is': 12,
 'where is the': 12,
 'where to go to': 12,
 'who do': 12,
 'would like it if': 12,
 'you could give me': 24,
 'you give me directions': 12,
 'you help me find': 12,
 'you help me locate': 12,
 'you inform me where': 12,
 'you point me towards': 12,
 'you tell me how': 12,
 'you tell me the': 12,
 'you tell me where': 24
}
