
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-04T13:12:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cddc456f5004dc5a1e9a71750c5cc901246639e0",
 "version": "1.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
