
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-06T23:35:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "63f32dc83d53cd2812105cce877f3b0aa2e372d5",
 "version": "2.9.5.post0.dev17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
