# Generated by Django 4.1.5 on 2023-02-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbles', '0012_audioscrobblertsvimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioscrobblertsvimport',
            name='processed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
