# coding: utf-8

"""
    Martlet Organization API

    Create/maintain organizations, access keys, addresses and permissions.   # noqa: E501

    OpenAPI spec version: 0.116.0
    Contact: apiteam@bmbix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bmb_martlet_organization_client
from bmb_martlet_organization_client.api.access_keys_api import AccessKeysApi  # noqa: E501
from bmb_martlet_organization_client.rest import ApiException


class TestAccessKeysApi(unittest.TestCase):
    """AccessKeysApi unit test stubs"""

    def setUp(self):
        self.api = AccessKeysApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete(self):
        """Test case for delete

        Delete an individual AccessKey  # noqa: E501
        """
        pass

    def test_index(self):
        """Test case for index

        Get the access keys for an organization.  # noqa: E501
        """
        pass

    def test_insert(self):
        """Test case for insert

        Create an access key  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
