
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-02T17:20:08-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe41c2a2c5fe06ce36673a69d039e69aa396a5c5",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
