# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TitleTest.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QBrush, QPixmap
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas, \
    NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure
import matplotlib.pyplot as plt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1360, 800)
        Form.setStyleSheet("#Form{border-image:url(head.png);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(14)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMaximumSize(QtCore.QSize(167755555, 80))
        self.widget.setMinimumSize(QtCore.QSize(1280, 80))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(64, 64))
        self.label.setMinimumSize(QtCore.QSize(64, 64))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem21 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem21)
        self.label_open = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_open.sizePolicy().hasHeightForWidth())
        self.label_open.setSizePolicy(sizePolicy)
        self.label_open.setObjectName("label_open")
        self.label_open.setMaximumSize(QtCore.QSize(32, 32))
        self.label_open.setMinimumSize(QtCore.QSize(32, 32))
        self.label_open.setToolTip("Open File")
        self.label_open.setToolTipDuration(3000)
        self.horizontalLayout.addWidget(self.label_open)
        spacerItem31 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem31)
        self.label_save = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_save.sizePolicy().hasHeightForWidth())
        self.label_save.setSizePolicy(sizePolicy)
        self.label_save.setObjectName("label_save")
        self.label_save.setMaximumSize(QtCore.QSize(32, 32))
        self.label_save.setMinimumSize(QtCore.QSize(32, 32))
        self.label_save.setToolTip("Save All")
        self.label_save.setToolTipDuration(3000)
        self.horizontalLayout.addWidget(self.label_save)
        spacerItem41 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem41)
        self.label_help = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_help.sizePolicy().hasHeightForWidth())
        self.label_help.setSizePolicy(sizePolicy)
        self.label_help.setObjectName("label")
        self.label_help.setToolTip("Help")
        self.label_help.setToolTipDuration(3000)
        self.label_help.setMaximumSize(QtCore.QSize(32, 32))
        self.label_help.setMinimumSize(QtCore.QSize(32, 32))
        self.horizontalLayout.addWidget(self.label_help)
        spacerItem1 = QtWidgets.QSpacerItem(280, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(8, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem4 = QtWidgets.QSpacerItem(8, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem5 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(14, 0, 14, 14)
        self.horizontalLayout_2.setSpacing(14)
        self.horizontalLayout_2.setObjectName("horizontalLayout")

        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setObjectName("widget_3")
        self.widget_3.setMaximumSize(QtCore.QSize(228, 11111111))
        self.widget_3.setMinimumSize(QtCore.QSize(228, 692))
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_1.setContentsMargins(14, 15, 14, 12)
        self.verticalLayout_1.setSpacing(0)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        # spacerItem6 = QtWidgets.QSpacerItem(1, 2, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        #
        self.widget_method = QtWidgets.QWidget(Form)
        self.widget_method.setObjectName("widget_method")
        self.widget_method.setMaximumSize(QtCore.QSize(150, 15))
        self.widget_method.setMinimumSize(QtCore.QSize(150, 15))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_method)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_method)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(14, 14))
        self.label_3.setMinimumSize(QtCore.QSize(14, 14))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget_method)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_1.addWidget(self.widget_method)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setWeight(500)
        buttonstyle = '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;font-family:"Microsoft YaHei 
        UI";font-size:10;font-weight:500;}QPushButton:hover{background:#7effb1;} '''
        spacerItem7 = QtWidgets.QSpacerItem(1, 15, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_1.addItem(spacerItem7)
        self.widget_toolbox = QtWidgets.QWidget(Form)
        self.widget_toolbox.setObjectName("widget_toolbox")
        self.widget_toolbox.setMaximumSize(QtCore.QSize(400, 500))
        self.widget_toolbox.setMinimumSize(QtCore.QSize(600, 500))
        self.toolBox = QtWidgets.QToolBox(self.widget_toolbox)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 400))
        self.toolBox.setMaximumSize(QtCore.QSize(200, 400))
        self.toolBox.setLineWidth(20)
        self.toolBox.setObjectName("toolBox")
        self.page_T1 = QtWidgets.QWidget(Form)
        self.page_T1.setMinimumSize(QtCore.QSize(150, 260))
        self.page_T1.setStyleSheet(" background-color:#ffffff;\n"
                                   "                   border:1px solid #CCCCCC;\n"
                                   "                   border-radius:6px")
        self.page_T1.setObjectName("page_T1")
        self.layout_T1 = QtWidgets.QVBoxLayout()
        self.layout_T1.setContentsMargins(10, 0, 10, 0)
        self.layout_T1.setObjectName("layout_T1")
        self.scroll1 = QtWidgets.QScrollArea()
        self.page_T1.setLayout(self.layout_T1)
        self.pushButton_01 = QtWidgets.QPushButton()
        self.pushButton_01.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_01.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_01.setText("Gaussian Noise")
        self.pushButton_01.setFont(font)
        self.pushButton_01.setObjectName("pushButton_01")
        self.layout_T1.addWidget(self.pushButton_01)
        self.pushButton_02 = QtWidgets.QPushButton()
        self.pushButton_02.setObjectName("pushButton_02")
        self.pushButton_02.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_02.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_02.setText("Undetermined")
        self.pushButton_02.setFont(font)
        self.layout_T1.addWidget(self.pushButton_02)
        self.pushButton_03 = QtWidgets.QPushButton()
        self.pushButton_03.setObjectName("pushButton_03")
        self.pushButton_03.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_03.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_03.setText("Undetermined")
        self.pushButton_03.setFont(font)
        self.layout_T1.addWidget(self.pushButton_03)
        self.pushButton_04 = QtWidgets.QPushButton()
        self.pushButton_04.setObjectName("pushButton_04")
        self.pushButton_04.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_04.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_04.setText("Undetermined")
        self.pushButton_04.setFont(font)
        self.layout_T1.addWidget(self.pushButton_04)
        self.scroll1.setWidget(self.page_T1)
        self.toolBox.addItem(self.scroll1, "")

        self.page_T2 = QtWidgets.QWidget()
        self.page_T2.setObjectName("page_T2")
        self.page_T2.setMinimumSize(QtCore.QSize(160, 260))
        self.page_T2.setStyleSheet(" background-color:#ffffff;\n"
                                   "                   border:1px solid #CCCCCC;\n"
                                   "                   border-radius:6px")
        self.layout_T2 = QtWidgets.QVBoxLayout()
        self.layout_T2.setContentsMargins(10, 0, 10, 0)
        self.layout_T2.setObjectName("layout_T2")
        self.scroll2 = QtWidgets.QScrollArea()
        self.page_T2.setLayout(self.layout_T2)
        self.pushButton_05 = QtWidgets.QPushButton()
        self.pushButton_05.setObjectName("pushButton_05")
        self.pushButton_05.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_05.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_05.setText("SMOTE")
        self.pushButton_05.setFont(font)
        self.layout_T2.addWidget(self.pushButton_05)
        self.pushButton_06 = QtWidgets.QPushButton()
        self.pushButton_06.setObjectName("pushButton_06")
        self.pushButton_06.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_06.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_06.setText("LLE")
        self.pushButton_06.setFont(font)
        self.layout_T2.addWidget(self.pushButton_06)
        self.pushButton_07 = QtWidgets.QPushButton()
        self.pushButton_07.setObjectName("pushButton_07")
        self.pushButton_07.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_07.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_07.setText("KNNMTD")
        self.pushButton_07.setFont(font)
        self.layout_T2.addWidget(self.pushButton_07)
        self.pushButton_08 = QtWidgets.QPushButton()
        self.pushButton_08.setObjectName("pushButton_08")
        self.pushButton_08.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_08.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_08.setText("MTD")
        self.pushButton_08.setFont(font)
        self.layout_T2.addWidget(self.pushButton_08)
        self.scroll2.setWidget(self.page_T2)
        self.toolBox.addItem(self.scroll2, "")

        self.page_T3 = QtWidgets.QWidget()
        self.page_T3.setObjectName("page_T3")
        self.page_T3.setMinimumSize(QtCore.QSize(160, 260))
        self.page_T3.setStyleSheet(" background-color:#ffffff;\n"
                                   "                   border:1px solid #CCCCCC;\n"
                                   "                   border-radius:6px")
        self.layout_T3 = QtWidgets.QVBoxLayout()
        self.layout_T3.setContentsMargins(10, 0, 10, 0)
        self.layout_T3.setObjectName("layout_T3")
        self.scroll3 = QtWidgets.QScrollArea()
        self.page_T3.setLayout(self.layout_T3)
        self.pushButton_09 = QtWidgets.QPushButton()
        self.pushButton_09.setObjectName("pushButton_09")
        self.pushButton_09.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_09.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_09.setText("GMM")
        self.pushButton_09.setFont(font)
        self.layout_T3.addWidget(self.pushButton_09)
        self.pushButton_10 = QtWidgets.QPushButton()
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_10.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_10.setText("Undetermined")
        self.pushButton_10.setFont(font)
        self.layout_T3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton()
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_11.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_11.setText("Undetermined")
        self.pushButton_11.setFont(font)
        self.layout_T3.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton()
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_12.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_12.setText("Undetermined")
        self.pushButton_12.setFont(font)
        self.layout_T3.addWidget(self.pushButton_12)
        self.scroll3.setWidget(self.page_T3)
        self.toolBox.addItem(self.scroll3, "")

        self.page_T4 = QtWidgets.QWidget()
        self.page_T4.setObjectName("page_T4")
        self.page_T4.setMinimumSize(QtCore.QSize(160, 260))
        self.page_T4.setStyleSheet(" background-color:#ffffff;\n"
                                   "                   border:1px solid #CCCCCC;\n"
                                   "                   border-radius:6px")
        self.layout_T4 = QtWidgets.QVBoxLayout()
        self.layout_T4.setContentsMargins(10, 0, 10, 0)
        self.layout_T4.setObjectName("layout_T4")
        self.scroll4 = QtWidgets.QScrollArea()
        self.page_T4.setLayout(self.layout_T4)
        self.pushButton_13 = QtWidgets.QPushButton()
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_13.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_13.setText("GAN")
        self.pushButton_13.setFont(font)
        self.layout_T4.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton()
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_14.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_14.setText("Undetermined")
        self.pushButton_14.setFont(font)
        self.layout_T4.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton()
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_15.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_15.setText("Undetermined")
        self.pushButton_15.setFont(font)
        self.layout_T4.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton()
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.setMinimumSize(QtCore.QSize(176, 30))
        self.pushButton_16.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_16.setText("Undetermined")
        self.pushButton_16.setFont(font)
        self.layout_T4.addWidget(self.pushButton_16)
        self.scroll4.setWidget(self.page_T4)
        self.toolBox.addItem(self.scroll4, "")
        self.page_T7 = QtWidgets.QWidget()
        self.page_T7.setGeometry(QtCore.QRect(50, 50, 141, 171))
        self.page_T7.setObjectName("page_T7")
        self.page_T7.setStyleSheet(" background-color:#ffffff;\n")
        self.toolBox.addItem(self.page_T7, "")
        self.verticalLayout_1.addWidget(self.widget_toolbox)

        spacerItem8 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_1.addItem(spacerItem8)
        self.widget_description = QtWidgets.QWidget(Form)
        self.widget_description.setObjectName("widget_description")
        self.widget_description.setMaximumSize(QtCore.QSize(120, 15))
        self.widget_description.setMinimumSize(QtCore.QSize(120, 15))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_description)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget_description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(14, 14))
        self.label_5.setMinimumSize(QtCore.QSize(14, 14))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget_description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_1.addWidget(self.widget_description)
        spacerItem9 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_1.addItem(spacerItem9)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget_3)
        self.plainTextEdit.setMinimumSize(200, 190)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit.setStyleSheet(" background-color:#ffffff;\n"
                                         "                   border:1px solid #CCCCCC;\n"
                                         "                   border-radius:6px")
        self.verticalLayout_1.addWidget(self.plainTextEdit)
        self.horizontalLayout_2.addWidget(self.widget_3)

        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setObjectName("widget_4")
        self.widget_4.setMaximumSize(QtCore.QSize(167755555, 11111111))
        self.widget_4.setMinimumSize(QtCore.QSize(534, 692))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(14)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_41 = QtWidgets.QWidget(Form)
        self.widget_41.setObjectName("widget_41")
        self.widget_41.setMaximumSize(QtCore.QSize(167755555, 175))
        self.widget_41.setMinimumSize(QtCore.QSize(534, 175))
        self.widget_para = QtWidgets.QWidget(Form)
        self.widget_para.setObjectName("widget_para")
        self.widget_para.setGeometry(QtCore.QRect(270, 100, 180, 30))
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.widget_para)
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_41.setSpacing(9)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_7 = QtWidgets.QLabel(self.widget_para)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(14, 14))
        self.label_7.setMinimumSize(QtCore.QSize(14, 14))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_41.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget_para)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_41.addWidget(self.label_8)




        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_41)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 25, 530, 150))
        self.page_0 = QtWidgets.QWidget()
        self.stackedWidget.addWidget(self.page_0)

        self.page_GNI = QtWidgets.QWidget()
        self.HLayout_GNI = QtWidgets.QHBoxLayout(self.page_GNI)
        self.HLayout_GNI.setSpacing(12)
        self.verticalLayout_GNI1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_GNI1.setSpacing(0)
        self.verticalLayout_GNI1.setObjectName("verticalLayout_GNI1")
        self.mean_para = QtWidgets.QLabel()
        self.mean_para.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:16px;font-weight:400;color:#898989;
                                                         line-height:26px ''')
        self.mean_para.setText("Mean")
        self.verticalLayout_GNI1.addWidget(self.mean_para)
        self.mean_value = QtWidgets.QDoubleSpinBox(self.page_GNI)
        self.mean_value.setAlignment(QtCore.Qt.AlignCenter)
        self.mean_value.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.mean_value.setMinimumSize(QtCore.QSize(140, 35))
        self.mean_value.setMaximumSize(QtCore.QSize(140, 35))
        self.verticalLayout_GNI1.addWidget(self.mean_value)
        spacerItem_11 = QtWidgets.QSpacerItem(280, 30, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_GNI1.addItem(spacerItem_11)
        self.HLayout_GNI.addLayout(self.verticalLayout_GNI1)
        self.verticalLayout_GNI2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_GNI2.setSpacing(0)
        self.var_para = QtWidgets.QLabel()
        self.var_para.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:16px;font-weight:400;color:#898989;
                                                                 line-height:26px ''')
        self.var_para.setText("Variance")
        self.verticalLayout_GNI2.addWidget(self.var_para)
        self.var_value = QtWidgets.QDoubleSpinBox(self.page_GNI)
        self.var_value.setAlignment(QtCore.Qt.AlignCenter)
        self.var_value.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.var_value.setMinimumSize(QtCore.QSize(140, 35))
        self.var_value.setMaximumSize(QtCore.QSize(140, 35))
        self.verticalLayout_GNI2.addWidget(self.var_value)
        spacerItem_12 = QtWidgets.QSpacerItem(280, 30, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_GNI2.addItem(spacerItem_12)
        self.HLayout_GNI.addLayout(self.verticalLayout_GNI2)
        self.stackedWidget.addWidget(self.page_GNI)

        self.page_SMOTE = QtWidgets.QWidget()
        self.page_SMOTE.setGeometry(QtCore.QRect(0, 10, 530, 10))
        self.HLayout_SMOTE = QtWidgets.QHBoxLayout(self.page_SMOTE)
        self.HLayout_SMOTE.setSpacing(12)
        self.verticalLayout_SMOTE = QtWidgets.QVBoxLayout()
        self.verticalLayout_SMOTE.setSpacing(0)
        self.verticalLayout_SMOTE.setObjectName("verticalLayout_SMOTE")
        self.kn_para_smote = QtWidgets.QLabel()
        self.kn_para_smote.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:16px;font-weight:400;color:#898989;
                                                                 line-height:26px ''')
        self.kn_para_smote.setText("Number of Neighbours")
        self.verticalLayout_SMOTE.addWidget(self.kn_para_smote)
        self.kn_value_smote = QtWidgets.QSpinBox(self.page_SMOTE)
        self.kn_value_smote.setMinimumSize(QtCore.QSize(140, 35))
        self.kn_value_smote.setMaximumSize(QtCore.QSize(140, 35))
        self.kn_value_smote.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.kn_value_smote.setAlignment(QtCore.Qt.AlignCenter)
        self.kn_value_smote.setMaximum(1000000)
        self.verticalLayout_SMOTE.addWidget(self.kn_value_smote)
        spacerItem_13 = QtWidgets.QSpacerItem(280, 30, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_SMOTE.addItem(spacerItem_13)
        self.HLayout_SMOTE.addLayout(self.verticalLayout_SMOTE)
        self.stackedWidget.addWidget(self.page_SMOTE)

        self.page_lle = QtWidgets.QWidget()
        self.HLayout_lle = QtWidgets.QHBoxLayout(self.page_lle)
        self.HLayout_lle.setSpacing(12)
        self.verticalLayout_lle1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_lle1.setSpacing(0)
        self.verticalLayout_lle1.setObjectName("verticalLayout_lle1")
        self.kn_para_lle = QtWidgets.QLabel()
        self.kn_para_lle.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:14px;font-weight:400;color:#898989;
                                                         line-height:26px ''')
        self.kn_para_lle.setText("Num_Neighbours")
        self.kn_para_lle.setToolTip("Number of Neighbours")
        self.kn_para_lle.setToolTipDuration(3000)
        self.verticalLayout_lle1.addWidget(self.kn_para_lle)
        self.kn_value_lle = QtWidgets.QSpinBox(self.page_lle)
        self.kn_value_lle.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.kn_value_lle.setAlignment(QtCore.Qt.AlignCenter)
        self.kn_value_lle.setMinimumSize(QtCore.QSize(140, 35))
        self.kn_value_lle.setMaximumSize(QtCore.QSize(140, 35))
        self.kn_value_lle.setMaximum(1000000)
        self.verticalLayout_lle1.addWidget(self.kn_value_lle)
        spacerItem_14 = QtWidgets.QSpacerItem(280, 30, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_lle1.addItem(spacerItem_14)
        self.HLayout_lle.addLayout(self.verticalLayout_lle1)
        self.verticalLayout_lle2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_lle2.setSpacing(0)
        self.reg_para = QtWidgets.QLabel()
        self.reg_para.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:14px;font-weight:400;color:#898989;
                                                                 line-height:26px ''')
        self.reg_para.setText("Regularization Factor")
        self.verticalLayout_lle2.addWidget(self.reg_para)
        self.reg_value = QtWidgets.QDoubleSpinBox(self.page_lle)
        self.reg_value.setMinimumSize(QtCore.QSize(140, 35))
        self.reg_value.setMaximumSize(QtCore.QSize(140, 35))
        self.reg_value.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.reg_value.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_lle2.addWidget(self.reg_value)
        spacerItem_15 = QtWidgets.QSpacerItem(280, 30, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_lle2.addItem(spacerItem_15)
        self.HLayout_lle.addLayout(self.verticalLayout_lle2)
        self.verticalLayout_lle3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_lle3.setSpacing(0)
        self.con_para = QtWidgets.QLabel()
        self.con_para.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:14px;font-weight:400;color:#898989;
                                                                         line-height:26px ''')
        self.con_para.setText("Num_Components")
        self.con_para.setToolTip("Number of Components")
        self.con_para.setToolTipDuration(3000)
        self.verticalLayout_lle3.addWidget(self.con_para)
        self.con_value = QtWidgets.QSpinBox(self.page_lle)
        self.con_value.setMinimumSize(QtCore.QSize(140, 35))
        self.con_value.setMaximumSize(QtCore.QSize(140, 35))
        self.con_value.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.con_value.setAlignment(QtCore.Qt.AlignCenter)
        self.con_value.setMaximum(1000000)
        self.verticalLayout_lle3.addWidget(self.con_value)
        spacerItem_16 = QtWidgets.QSpacerItem(280, 30, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_lle3.addItem(spacerItem_16)
        self.HLayout_lle.addLayout(self.verticalLayout_lle3)
        self.stackedWidget.addWidget(self.page_lle)

        self.page_knnmtd = QtWidgets.QWidget()
        self.HLayout_knnmtd = QtWidgets.QHBoxLayout(self.page_knnmtd)
        self.HLayout_knnmtd.setSpacing(12)
        self.verticalLayout_knnmtd = QtWidgets.QVBoxLayout()
        self.verticalLayout_knnmtd.setSpacing(0)
        self.verticalLayout_knnmtd.setObjectName("verticalLayout_knnmtd")
        self.kn_para_knnmtd = QtWidgets.QLabel()
        self.kn_para_knnmtd.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:16px;font-weight:400;color:#898989;
                                                                         line-height:26px ''')
        self.kn_para_knnmtd.setText("Number of Neighbours")

        self.verticalLayout_knnmtd.addWidget(self.kn_para_knnmtd)
        self.kn_value_knnmtd = QtWidgets.QSpinBox(self.page_knnmtd)
        self.kn_value_knnmtd.setMinimumSize(QtCore.QSize(140, 35))
        self.kn_value_knnmtd.setMaximumSize(QtCore.QSize(140, 35))
        self.kn_value_knnmtd.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.kn_value_knnmtd.setAlignment(QtCore.Qt.AlignCenter)
        self.kn_value_knnmtd.setMaximum(1000000)
        self.verticalLayout_knnmtd.addWidget(self.kn_value_knnmtd)
        spacerItem_17 = QtWidgets.QSpacerItem(280, 30, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_knnmtd.addItem(spacerItem_17)
        self.HLayout_knnmtd.addLayout(self.verticalLayout_knnmtd)
        self.stackedWidget.addWidget(self.page_knnmtd)

        self.page_gmm = QtWidgets.QWidget()
        self.HLayout_gmm = QtWidgets.QHBoxLayout(self.page_gmm)
        self.HLayout_gmm.setSpacing(12)
        self.verticalLayout_gmm = QtWidgets.QVBoxLayout()
        self.verticalLayout_gmm.setSpacing(0)
        self.verticalLayout_gmm.setObjectName("verticalLayout_gmm")
        self.kn_para_gmm = QtWidgets.QLabel()
        self.kn_para_gmm.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:16px;font-weight:400;color:#898989;
                                                                                line-height:26px ''')
        self.kn_para_gmm.setText("Number of Neighbours")

        self.verticalLayout_gmm.addWidget(self.kn_para_gmm)
        self.kn_value_gmm = QtWidgets.QSpinBox(self.page_gmm)
        self.kn_value_gmm.setMinimumSize(QtCore.QSize(140, 35))
        self.kn_value_gmm.setMaximumSize(QtCore.QSize(140, 35))
        self.kn_value_gmm.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.kn_value_gmm.setAlignment(QtCore.Qt.AlignCenter)
        self.kn_value_gmm.setMaximum(1000000)
        self.verticalLayout_gmm.addWidget(self.kn_value_gmm)
        spacerItem_18 = QtWidgets.QSpacerItem(280, 30, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_gmm.addItem(spacerItem_18)
        self.HLayout_gmm.addLayout(self.verticalLayout_gmm)
        self.stackedWidget.addWidget(self.page_gmm)

        self.page_gan = QtWidgets.QWidget()
        self.VLayout_gan = QtWidgets.QVBoxLayout(self.page_gan)
        self.VLayout_gan.setSpacing(9)
        self.HLayout_gan1 = QtWidgets.QHBoxLayout(self.page_gan)
        self.HLayout_gan1.setSpacing(15)
        self.verticalLayout_gan1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_gan1.setSpacing(8)
        self.verticalLayout_gan1.setObjectName("verticalLayout_gan1")
        self.epoch_para_gan = QtWidgets.QLabel()
        self.epoch_para_gan.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:14px;font-weight:400;color:#898989;
                                                                         line-height:26px ''')
        self.epoch_para_gan.setText("Number of Epochs")
        self.verticalLayout_gan1.addWidget(self.epoch_para_gan)
        self.epoch_value_gan = QtWidgets.QSpinBox(self.page_gan)
        self.epoch_value_gan.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.epoch_value_gan.setAlignment(QtCore.Qt.AlignCenter)
        self.epoch_value_gan.setMaximum(1000000)
        self.epoch_value_gan.setMinimumSize(QtCore.QSize(140, 35))
        self.epoch_value_gan.setMaximumSize(QtCore.QSize(140, 35))
        self.verticalLayout_gan1.addWidget(self.epoch_value_gan)

        self.HLayout_gan1.addLayout(self.verticalLayout_gan1)
        self.verticalLayout_gan2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_gan2.setSpacing(8)
        self.lr_para_gan = QtWidgets.QLabel()
        self.lr_para_gan.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:14px;font-weight:400;color:#898989;
                                                                                 line-height:26px ''')
        self.lr_para_gan.setText("Learning Rate")
        self.verticalLayout_gan2.addWidget(self.lr_para_gan)
        self.lr_value_gan = QtWidgets.QDoubleSpinBox(self.page_gan)
        self.lr_value_gan.setMinimumSize(QtCore.QSize(140, 35))
        self.lr_value_gan.setMaximumSize(QtCore.QSize(140, 35))
        self.lr_value_gan.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.lr_value_gan.setAlignment(QtCore.Qt.AlignCenter)
        self.lr_value_gan.setMaximum(1)
        self.lr_value_gan.setDecimals(5)
        self.verticalLayout_gan2.addWidget(self.lr_value_gan)
        self.HLayout_gan1.addLayout(self.verticalLayout_gan2)

        self.verticalLayout_gan3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_gan3.setSpacing(8)
        self.batch_para_gan = QtWidgets.QLabel()
        self.batch_para_gan.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:14px;font-weight:400;color:#898989;
                                                                                         line-height:26px ''')
        self.batch_para_gan.setText("Batch Size")
        self.verticalLayout_gan3.addWidget(self.batch_para_gan)
        self.batch_value_gan = QtWidgets.QSpinBox(self.page_gan)
        self.batch_value_gan.setMinimumSize(QtCore.QSize(140, 35))
        self.batch_value_gan.setMaximumSize(QtCore.QSize(140, 35))
        self.batch_value_gan.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.batch_value_gan.setAlignment(QtCore.Qt.AlignCenter)
        self.batch_value_gan.setMaximum(1000)
        self.verticalLayout_gan3.addWidget(self.batch_value_gan)
        self.HLayout_gan1.addLayout(self.verticalLayout_gan3)
        self.HLayout_gan2 = QtWidgets.QHBoxLayout(self.page_gan)
        self.HLayout_gan2.setSpacing(12)
        self.verticalLayout_gan4 = QtWidgets.QVBoxLayout(self.page_gan)
        self.verticalLayout_gan4.setSpacing(8)
        self.verticalLayout_gan4.setObjectName("verticalLayout_gan4")
        self.latent_para_gan = QtWidgets.QLabel()
        self.latent_para_gan.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:14px;font-weight:400;color:#898989;
                                                                                 line-height:26px ''')
        self.latent_para_gan.setText("Latent Dimension")
        self.verticalLayout_gan4.addWidget(self.latent_para_gan)
        self.latent_value_gan = QtWidgets.QSpinBox(self.page_gan)
        self.latent_value_gan.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.latent_value_gan.setAlignment(QtCore.Qt.AlignCenter)
        self.latent_value_gan.setMinimumSize(QtCore.QSize(140, 35))
        self.latent_value_gan.setMaximumSize(QtCore.QSize(140, 35))
        self.latent_value_gan.setMaximum(1000)
        self.verticalLayout_gan4.addWidget(self.latent_value_gan)
        self.HLayout_gan2.addLayout(self.verticalLayout_gan4)
        self.VLayout_gan.addLayout(self.HLayout_gan1)
        self.VLayout_gan.addLayout(self.HLayout_gan2)
        self.stackedWidget.addWidget(self.page_gan)

        self.widget_42 = QtWidgets.QWidget(Form)
        self.widget_42.setObjectName("widget_42")
        self.widget_42.setMaximumSize(QtCore.QSize(167755555, 11111111))
        self.widget_42.setMinimumSize(QtCore.QSize(534, 502))
        self.widget_generation = QtWidgets.QWidget(Form)
        self.widget_generation.setObjectName("widget_para")
        self.widget_generation.setGeometry(QtCore.QRect(272, 290, 165, 30))
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.widget_generation)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setSpacing(9)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_9 = QtWidgets.QLabel(self.widget_generation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(14, 14))
        self.label_9.setMinimumSize(QtCore.QSize(14, 14))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_42.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget_generation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_42.addWidget(self.label_10)
        self.widget_numpara = QtWidgets.QWidget(Form)
        self.widget_numpara.setObjectName("widget_numpara")
        self.widget_numpara.setGeometry(QtCore.QRect(257, 322, 534, 40))
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.widget_numpara)
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_43.setSpacing(0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.numgen_para = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.numgen_para.sizePolicy().hasHeightForWidth())
        self.numgen_para.setSizePolicy(sizePolicy)
        self.numgen_para.setObjectName("numgen_para")
        self.numgen_para.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:14px;font-weight:400;color:#898989;
                                                                                line-height:26px ''')
        self.numgen_para.setText("Number of Generated Samples")
        self.num_gen_value = QtWidgets.QSpinBox()
        self.num_gen_value.setMinimumSize(QtCore.QSize(140, 30))
        self.num_gen_value.setMaximumSize(QtCore.QSize(140, 30))
        self.num_gen_value.setMaximum(1000000)
        self.num_gen_value.setValue(1000)
        self.num_gen_value.setValue(1000)
        self.num_gen_value.setStyleSheet('''border:1px solid #CCCCCC ''')
        self.num_gen_value.setAlignment(QtCore.Qt.AlignCenter)
        self.pushButton_start = QtWidgets.QPushButton()
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_start.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_start.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_start.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_start.setText("START")
        self.pushButton_start.setFont(font)

        spacerItem11 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addWidget(self.numgen_para)
        self.horizontalLayout_43.addWidget(self.num_gen_value)
        self.horizontalLayout_43.addItem(spacerItem11)
        self.horizontalLayout_43.addWidget(self.pushButton_start)
        self.widget_pca = QtWidgets.QWidget(Form)
        self.widget_pca.setObjectName("widget_pca")
        self.widget_pca.setGeometry(QtCore.QRect(260, 365, 534, 1000))
        self.PCADisplayGB = QtWidgets.QGroupBox(self.widget_pca)
        self.PCADisplayGB.setStyleSheet('''border:1px solid #FFFFFF ''')
        self.fig_pca = plt.Figure(figsize=(5, 3))
        self.pca_canva = FigureCanvas(self.fig_pca)
        self.axes_pca = self.pca_canva.figure.subplots()
        self.fig_pca.subplots_adjust(top=0.985, bottom=0.085, left=0.06, right=0.975,
                                     hspace=0.2,
                                     wspace=0.2)
        self.toolbar_pca = NavigationToolbar(self.pca_canva, self)
        self.layout_visual = QtWidgets.QVBoxLayout()
        self.layout_visual.addWidget(self.pca_canva)
        self.layout_visual.addWidget(self.toolbar_pca)
        self.PCADisplayGB.setLayout(self.layout_visual)
        self.widget_save = QtWidgets.QWidget(Form)
        self.widget_save.setObjectName("widget_save")
        self.widget_save.setGeometry(QtCore.QRect(257, 732, 534, 45))
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.widget_save)
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_44.setSpacing(0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.pushButton_savedata = QtWidgets.QPushButton()
        self.pushButton_savedata.setObjectName("pushButton_savedata")
        self.pushButton_savedata.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_savedata.setMaximumSize(QtCore.QSize(200, 40))
        self.pushButton_savedata.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_savedata.setText("Save Data")
        self.pushButton_savedata.setFont(font)
        self.pushButton_savemodel = QtWidgets.QPushButton()
        self.pushButton_savemodel.setObjectName("pushButton_savemodel")
        self.pushButton_savemodel.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_savemodel.setMaximumSize(QtCore.QSize(200, 40))
        self.pushButton_savemodel.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_savemodel.setText("Save Model")
        self.pushButton_savemodel.setFont(font)

        self.horizontalLayout_44.addWidget(self.pushButton_savedata)
        self.horizontalLayout_44.addWidget(self.pushButton_savemodel)
        self.verticalLayout_2.addWidget(self.widget_41)
        self.verticalLayout_2.addWidget(self.widget_42)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setObjectName("widget_5")
        self.widget_5.setMaximumSize(QtCore.QSize(167755555, 11111111))
        self.widget_5.setMinimumSize(QtCore.QSize(462, 692))
        self.widget_test = QtWidgets.QWidget(self.widget_5)
        self.widget_test.setObjectName("widget_para")
        self.widget_test.setGeometry(QtCore.QRect(10, 10, 127, 30))
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.widget_test)
        self.horizontalLayout_45.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_45.setSpacing(8)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_11 = QtWidgets.QLabel(self.widget_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMaximumSize(QtCore.QSize(14, 14))
        self.label_11.setMinimumSize(QtCore.QSize(14, 14))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_45.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_45.addWidget(self.label_12)

        self.widget_test1 = QtWidgets.QWidget(self.widget_5)
        self.widget_test1.setObjectName("widget_test1")
        self.widget_test1.setGeometry(QtCore.QRect(10, 65, 562, 400))
        self.TESTDisplayGB1 = QtWidgets.QGroupBox(self.widget_test1)
        self.TESTDisplayGB1.setFont(font)
        self.TESTDisplayGB1.setStyleSheet('''border:1px solid #FFFFFF ''')
        self.TESTDisplayGB1.setAlignment(QtCore.Qt.AlignCenter)
        self.fig_test1 = plt.Figure(figsize=(5.0, 2))
        self.test1_canva = FigureCanvas(self.fig_test1)
        self.fig_test1.subplots_adjust(top=0.95, bottom=0.155, left=0.09, right=0.978,
                                       hspace=0.2,
                                       wspace=0.2)
        self.axes_test1 = self.test1_canva.figure.subplots()
        self.test_before = QtWidgets.QLabel()
        self.test_before.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:16px;font-weight:400;color:#333333;
                                                                                line-height:26px ''')
        self.test_before.setText("Before Data Augmentation")
        self.test_visual1 = QtWidgets.QVBoxLayout()
        self.test_visual1.setContentsMargins(0, 0, 0, 0)
        self.evaluate_before = QtWidgets.QLabel(self.widget_5)
        self.evaluate_before.setGeometry(QtCore.QRect(205, 295, 350, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.evaluate_before.sizePolicy().hasHeightForWidth())
        self.evaluate_before.setSizePolicy(sizePolicy)
        self.evaluate_before.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:14px;font-weight:400;color:#333333;
                                                                                        line-height:26px ''')
        self.evaluate_before.setText("Evaluate Index：")
        self.test_visual1.addWidget(self.test_before)
        self.test_visual1.addWidget(self.test1_canva)
        self.TESTDisplayGB1.setLayout(self.test_visual1)
        self.widget_test2 = QtWidgets.QWidget(self.widget_5)
        self.widget_test2.setObjectName("widget_test2")
        self.widget_test2.setGeometry(QtCore.QRect(10, 340, 562, 440))
        self.TESTDisplayGB2 = QtWidgets.QGroupBox(self.widget_test2)
        self.TESTDisplayGB2.setFont(font)
        self.TESTDisplayGB2.setStyleSheet('''border:1px solid #FFFFFF ''')
        self.TESTDisplayGB2.setAlignment(QtCore.Qt.AlignCenter)
        self.fig_test2 = plt.Figure(figsize=(5, 2))
        self.test2_canva = FigureCanvas(self.fig_test2)
        self.fig_test2.subplots_adjust(top=0.95, bottom=0.155, left=0.09, right=0.978,
                                       hspace=0.2,
                                       wspace=0.2)
        self.axes_test2 = self.test2_canva.figure.subplots()
        self.test_after = QtWidgets.QLabel()
        self.test_after.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:16px;font-weight:400;color:#333333;
                                                                                        line-height:26px ''')
        self.test_after.setText(
            "After Data Augmentation")  # self.toolbar_test1 = NavigationToolbar(self.test1_canva, self)
        self.test_visual2 = QtWidgets.QVBoxLayout()
        self.test_visual2.setContentsMargins(0, 0, 0, 0)
        self.evaluate_after = QtWidgets.QLabel(self.widget_5)
        self.evaluate_after.setGeometry(QtCore.QRect(205, 570, 350, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.evaluate_after.sizePolicy().hasHeightForWidth())
        self.evaluate_after.setSizePolicy(sizePolicy)
        self.evaluate_after.setStyleSheet('''font-family:"Microsoft YaHei UI";font-size:14px;font-weight:400;color:#333333;
                                                                                                line-height:26px ''')
        self.evaluate_after.setText("Evaluate Index：")
        self.test_visual2.addWidget(self.test_after)
        self.test_visual2.addWidget(self.test2_canva)
        self.pushButton_saveresult = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_saveresult.setGeometry(QtCore.QRect(165, 627, 200, 40))
        self.pushButton_saveresult.setStyleSheet(
            '''QPushButton{background:#52626C;border-radius:6px;color:#ffffff;}QPushButton:hover{background:#7effb1;} ''')
        self.pushButton_saveresult.setText("Save Test Result")
        self.pushButton_saveresult.setFont(font)

        # self.test_visual.addWidget(self.toolbar_test1)
        self.TESTDisplayGB2.setLayout(self.test_visual2)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.widget_2)

        self.pushButton_01.clicked.connect(Form.click_pushButton_01)
        self.pushButton_05.clicked.connect(Form.click_pushButton_05)
        self.pushButton_06.clicked.connect(Form.click_pushButton_06)
        self.pushButton_07.clicked.connect(Form.click_pushButton_07)
        self.pushButton_08.clicked.connect(Form.click_pushButton_08)
        self.pushButton_09.clicked.connect(Form.click_pushButton_09)
        self.pushButton_13.clicked.connect(Form.click_pushButton_13)
        self.pushButton_start.clicked.connect(Form.begin_gen)
        self.pushButton_savedata.clicked.connect(Form.save_data)
        self.pushButton_savemodel.clicked.connect(Form.save_model)
        self.pushButton_saveresult.clicked.connect(Form.save_test_result)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "图标"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.pushButton.setToolTip(_translate("Form", "<html><head/><body><p>最小化</p></body></html>"))
        self.pushButton.setText(_translate("Form", "-"))
        self.pushButton_2.setToolTip(_translate("Form", "<html><head/><body><p>最大化</p></body></html>"))
        self.pushButton_2.setText(_translate("Form", "O"))
        self.pushButton_3.setToolTip(_translate("Form", "<html><head/><body><p>关闭</p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "X"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.scroll1), _translate("MainWindow", "Noise Injection"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.scroll2), _translate("MainWindow", "Interpolation"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.scroll3), _translate("MainWindow", "Probability Model"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.scroll4), _translate("MainWindow", "Deep Learning"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_T7), _translate("MainWindow", "Back"))
