
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-04T12:30:37-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d1d104d9894ed38f7b68fd4b4058d1d2824d5d1",
 "version": "0.0.80"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
