# Generated by Django 3.2.7 on 2022-08-04 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_workorder_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bvn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employerAddress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employerName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idType',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landlordAddress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landlordName',
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletedViaCascade', models.BooleanField(default=False, editable=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('deletedById', models.UUIDField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('employerName', models.CharField(blank=True, db_column='employerName', max_length=255, null=True)),
                ('dateOfBirth', models.DateField()),
                ('country', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('placeOfWork', models.TextField(blank=True, db_column='placeOfWork', null=True)),
                ('officeAddress', models.TextField(blank=True, db_column='landlordAddress', null=True)),
                ('landlordName', models.CharField(db_column='landlordName', max_length=255)),
                ('bvn', models.CharField(blank=True, max_length=11, null=True)),
                ('postCode', models.CharField(blank=True, max_length=50, null=True)),
                ('accountNumber', models.CharField(max_length=50)),
                ('undertaking', models.CharField(blank=True, max_length=150, null=True)),
                ('transformer', models.CharField(blank=True, max_length=150, null=True)),
                ('accountType', models.CharField(db_column='accountType', max_length=30)),
                ('idNumber', models.CharField(db_column='idNumber', max_length=30)),
                ('idType', models.CharField(blank=True, db_column='idType', max_length=150, null=True)),
                ('feeder', models.CharField(blank=True, max_length=255, null=True)),
                ('tariffClass', models.CharField(blank=True, max_length=255, null=True)),
                ('businessUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.businessunit')),
                ('createdBy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
