# Generated by Django 3.2.7 on 2022-09-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_bedroom_workorderbedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderservice',
            name='bedrooms',
            field=models.ManyToManyField(blank=True, null=True, to='app.Bedroom'),
        ),
    ]
