
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-27T13:22:37+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "17f80b6184a5c326fb20c28105fbfdc14fcf1dfd",
 "version": "0.29.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
