
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-06T10:13:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "647c895e423ad2bf853cd858ecd6dc88636e4859",
 "version": "1.7.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
