
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-17T12:13:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e86534d0b5ca5d07b4043825c3d793b45178bc0",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
