
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-03T13:48:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9e8d5bcb0b5e615245776d57e83903bcc94b84f0",
 "version": "0.50.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
