# Generated by Django 4.1.5 on 2023-03-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_album_theaudiodb_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='theaudiodb_year_released',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
