# Generated by Django 4.1.5 on 2023-02-19 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('scrobbles', '0020_alter_audioscrobblertsvimport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrobble',
            name='book',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='books.book',
            ),
        ),
    ]
