
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-04T17:26:21-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "8262e546071e417b5b764b2572ef51bea3a7b68d",
 "version": "v0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
