# Version file autogenerated by the build process
version = '0.10.0-beta9'
build = 1094
vcs_info = 'Git SHA1 6a20a2c3 committed on 2023-03-02'
package_name = 'kintyre-splunk-conf'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.10.0-beta9"\nKSCONF_BUILD="1094"\nKSCONF_VCS_INFO="Git SHA1 6a20a2c3 committed on 2023-03-02"')
