
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-06T17:28:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e9c45114e7ef07f292245d970ceb778c66ad42f",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
