season = "2022-23"

team_names = ["Calcit Volley",
              "FužinarSijMetalRavne",
              "HišaNaKolesihTriglav",
              "Salonit Anhovo",
              "ACH Volley Ljubljana",
              "Črnuče",
              "Merkur Maribor",
              "Panvita Pomgrad"]

teams = {
    "Calcit Volley" : {"1": "Planinšič Uroš",
                       "2": "Mujanović Nik",
                       "5": "Vinkovič Dino",
                       "6": "Lazar Luka",
                       "8": "Klobučar Jan",
                       "10": "Košenina Alan",
                       "11": "Arsenoski Miloš",
                       "12": "Okroglič Jure",
                       "13": "Sosa Luis",
                       "23": "Aponza Daniel",
                       "77": "Pavlovič Uroš"},
    "FužinarSijMetalRavne": {"1": "Cafuta Miha",
                             "3": "Lednik Nace",
                             "4": "Križanič Bor",
                             "5": "Knuplež Jani",
                             "6": "Ranc David",
                             "7": "Bregar Miha",
                             "9": "Erpič Uroš",
                             "10": "Makaš Emir",
                             "11": "Levar Uroš",
                             "12": "Hribernik Žiga",
                             "14": "Vučetić Luka",
                             "23": "Ranc Vid"},
    "HišaNaKolesihTriglav": {"1": "Ibrišimovič Gal",
                             "3": "Nanut Maj",
                             "6": "Tučen Uroš",
                             "7": "Adžović Adi",
                             "9": "Rotar Bor Jese",
                             "11": "Snedec Amadej",
                             "12": "Jovović Đorđe",
                             "13": "Mali Miha",
                             "15": "Šikanič Aljoša",
                             "16": "Glamočanin Jure",
                             "17": "Fajfar Matic"},
    "Salonit Anhovo": {"1": "Kodrič Erik",
                       "2": "Stojanovič Aleksander",
                       "3": "Šarić Danijel",
                       "5": "Hesselholt Joachim",
                       "6": "Karnel Irenej",
                       "7": "Jeklin Primož",
                       "8": "Godnič Jani",
                       "9": "Kavčič Jakob",
                       "10": "Maretič Lian Svit",
                       "11": "Bojić Slobodan",
                       "12": "Okroglič Grega",
                       "13": "Kovačič Aleks",
                       "15": "Vrtovec Matic",
                       "17": "Maksimović Marko"},
    "ACH Volley Ljubljana": {"1": "Mejal Primož",
                             "5": "Šket Alen",
                             "8": "Mašulović Nemanja",
                             "9": "Todorović Vuk",
                             "10": "Bošnjak Črtomir",
                             "11": "Koncilja Danijel",
                             "12": "Šestan Filip",
                             "13": "Kovačič Jani",
                             "14": "Gjorgiev Nikola",
                             "17": "Videčnik Matic",
                             "18": "Kök Matej",
                             "19": "Šen Klemen"},
    "Črnuče": {"2": "Mihelčič Gregor",
               "6": "Karadža Pevc Matevž",
               "8": "Verdinek Jožef",
               "9": "Rojnik Matic",
               "10": "Oman Jurij",
               "11": "Sešek Jaka",
               "13": "Marovt Luka",
               "15": "Jančič Jan Karl",
               "16": "Valenčič Martin",
               "19": "Ramšak Vid",
               "33": "Česnovar Matic"},
    "Merkur Maribor": {"2": "Jevšnik Jaka",
                       "3": "Vodušek Timotej",
                       "4": "Pernuš Gregor",
                       "5": "Adžović Sani",
                       "6": "McConnell Connor",
                       "8": "Bračko Rok",
                       "9": "Kumer Žiga",
                       "10": "Kržič Janž Janez",
                       "11": "Donik Žiga",
                       "12": "Leva Filip",
                       "13": "Fink Miha",
                       "14": "Najdič Nejc",
                       "16": "Iršič Jaka",
                       "42": "Peruničić Nemanja"},
    "Panvita Pomgrad": {"1": "Rajnar Urban",
                        "5": "Šormaz Nenad",
                        "6": "Avšič Tine",
                        "7": "Drvarič Urban",
                        "8": "Vrabl Tin",
                        "10": "Rojnik Jakob",
                        "11": "Kovačič Tit",
                        "12": "Legen Nik",
                        "13": "Milovanović Marko",
                        "14": "Bedrač Žan",
                        "15": "Fužir Urban",
                        "16": "Novak David"},
}