# Generated by Django 3.2.6 on 2021-08-15 00:29

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracesetting",
            name="stacktrace_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="trace",
            name="data",
            field=jsonfield.fields.JSONField(),
        ),
    ]
