# coding: utf-8

"""
    RIME Rest API

    API methods for RIME. Must be authenticated with `rime-api-key` header.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: dev@robustintelligence.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ModelModelLoadingInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'path': 'str',
        'params': 'str'
    }

    attribute_map = {
        'path': 'path',
        'params': 'params'
    }

    def __init__(self, path=None, params=None):  # noqa: E501
        """ModelModelLoadingInfo - a model defined in Swagger"""  # noqa: E501
        self._path = None
        self._params = None
        self.discriminator = None
        if path is not None:
            self.path = path
        if params is not None:
            self.params = params

    @property
    def path(self):
        """Gets the path of this ModelModelLoadingInfo.  # noqa: E501


        :return: The path of this ModelModelLoadingInfo.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this ModelModelLoadingInfo.


        :param path: The path of this ModelModelLoadingInfo.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def params(self):
        """Gets the params of this ModelModelLoadingInfo.  # noqa: E501

        rime-engine types this as a generic dictionary, so encode user-defined json for now.  # noqa: E501

        :return: The params of this ModelModelLoadingInfo.  # noqa: E501
        :rtype: str
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this ModelModelLoadingInfo.

        rime-engine types this as a generic dictionary, so encode user-defined json for now.  # noqa: E501

        :param params: The params of this ModelModelLoadingInfo.  # noqa: E501
        :type: str
        """

        self._params = params

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelModelLoadingInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelModelLoadingInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
