
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-03T17:44:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "023eb782788fb0517b24bf47fa4ea115664062c6",
 "version": "4.9.69"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
