
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-06T06:25:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6effb6289c9f91a909a84678e8488cd1b3e690b",
 "version": "1.18.2.post0.dev173"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
