# coding: utf-8

"""
    Synctera API

    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>   # noqa: E501

    The version of the OpenAPI document: 0.38.0
    Contact: dev@swadesh.co
    Generated by: https://openapi-generator.tech
"""


from inspect import getfullargspec
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class CardStatusReasonCode(str, Enum):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """

    NEW = 'NEW'
    REQ = 'REQ'
    INA = 'INA'
    UNK = 'UNK'
    NEG = 'NEG'
    REV = 'REV'
    SUS = 'SUS'
    OUT = 'OUT'
    FRD = 'FRD'
    MAT = 'MAT'
    LOS = 'LOS'
    CLO = 'CLO'
    COM = 'COM'
    TMP = 'TMP'
    PRC = 'PRC'
    ISS = 'ISS'
    EXP = 'EXP'
    KYC = 'KYC'
    INF = 'INF'
    ACT = 'ACT'
    AUX = 'AUX'
    PIN = 'PIN'
    STO = 'STO'
    ADD = 'ADD'
    NAM = 'NAM'
    SSN = 'SSN'
    DOB = 'DOB'
    EML = 'EML'
    PHO = 'PHO'
    FUL = 'FUL'
    OTH = 'OTH'

