
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "authors": [
  "Padraic Shafer"
 ],
 "date": "2023-03-05T09:02:26-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "be0091e43b964e0aed9d14be638fab0bbe730760",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
