# Generated by Django 4.1.5 on 2023-01-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrobble',
            name='counted',
            field=models.BooleanField(default=False),
        ),
    ]
