# Generated by Django 4.1.5 on 2023-02-07 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrobbles', '0016_audioscrobblertsvimport_process_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioscrobblertsvimport',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
