
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-27T15:57:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "69f916e6b3d8951ade8331b3db6dd7d676cd8176",
 "version": "1.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
