"""empty message

Revision ID: c0ed3ac0d69e
Revises: 8cabe970f3af
Create Date: 2023-02-28 11:59:24.229033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0ed3ac0d69e'
down_revision = '8cabe970f3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('img_render')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_render', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
