"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import th2_grpc_common.common_pb2
import th2_grpc_data_provider.data_provider_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class IntervalInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    LAST_EVENT_ID_FIELD_NUMBER: builtins.int
    LAST_MESSAGE_IDS_FIELD_NUMBER: builtins.int
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def last_event_id(self) -> th2_grpc_common.common_pb2.EventID: ...
    @property
    def last_message_ids(self) -> global___MessageIDs: ...
    def __init__(self,
        *,
        start_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        end_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        last_event_id: typing.Optional[th2_grpc_common.common_pb2.EventID] = ...,
        last_message_ids: typing.Optional[global___MessageIDs] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["end_time",b"end_time","last_event_id",b"last_event_id","last_message_ids",b"last_message_ids","last_state",b"last_state","start_time",b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["end_time",b"end_time","last_event_id",b"last_event_id","last_message_ids",b"last_message_ids","last_state",b"last_state","start_time",b"start_time"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["last_state",b"last_state"]) -> typing.Optional[typing_extensions.Literal["last_event_id","last_message_ids"]]: ...
global___IntervalInfo = IntervalInfo

class MessageIDs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MESSAGE_IDS_FIELD_NUMBER: builtins.int
    @property
    def message_ids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[th2_grpc_common.common_pb2.MessageID]: ...
    def __init__(self,
        *,
        message_ids: typing.Optional[typing.Iterable[th2_grpc_common.common_pb2.MessageID]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message_ids",b"message_ids"]) -> None: ...
global___MessageIDs = MessageIDs

class CrawlerInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> global___CrawlerId: ...
    def __init__(self,
        *,
        id: typing.Optional[global___CrawlerId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___CrawlerInfo = CrawlerInfo

class CrawlerId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___CrawlerId = CrawlerId

class DataProcessorInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    name: typing.Text
    version: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        version: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","version",b"version"]) -> None: ...
global___DataProcessorInfo = DataProcessorInfo

class EventDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    EVENT_DATA_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> global___CrawlerId: ...
    @property
    def event_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[th2_grpc_data_provider.data_provider_pb2.EventResponse]: ...
    def __init__(self,
        *,
        id: typing.Optional[global___CrawlerId] = ...,
        event_data: typing.Optional[typing.Iterable[th2_grpc_data_provider.data_provider_pb2.EventResponse]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_data",b"event_data","id",b"id"]) -> None: ...
global___EventDataRequest = EventDataRequest

class MessageDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    MESSAGE_DATA_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> global___CrawlerId: ...
    @property
    def message_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[th2_grpc_data_provider.data_provider_pb2.MessageGroupResponse]: ...
    def __init__(self,
        *,
        id: typing.Optional[global___CrawlerId] = ...,
        message_data: typing.Optional[typing.Iterable[th2_grpc_data_provider.data_provider_pb2.MessageGroupResponse]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","message_data",b"message_data"]) -> None: ...
global___MessageDataRequest = MessageDataRequest

class EventResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> th2_grpc_common.common_pb2.EventID: ...
    @property
    def status(self) -> global___Status: ...
    def __init__(self,
        *,
        id: typing.Optional[th2_grpc_common.common_pb2.EventID] = ...,
        status: typing.Optional[global___Status] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","status",b"status"]) -> None: ...
global___EventResponse = EventResponse

class MessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IDS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    @property
    def ids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[th2_grpc_common.common_pb2.MessageID]: ...
    @property
    def status(self) -> global___Status: ...
    def __init__(self,
        *,
        ids: typing.Optional[typing.Iterable[th2_grpc_common.common_pb2.MessageID]] = ...,
        status: typing.Optional[global___Status] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ids",b"ids","status",b"status"]) -> None: ...
global___MessageResponse = MessageResponse

class Status(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HANDSHAKE_REQUIRED_FIELD_NUMBER: builtins.int
    handshake_required: builtins.bool
    def __init__(self,
        *,
        handshake_required: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["handshake_required",b"handshake_required"]) -> None: ...
global___Status = Status
