# Generated by Django 4.1.5 on 2023-01-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_series_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='run_time_ticks',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
