
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-07T11:46:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0681f17ed0b0c0d33ca50df1b9f012651b2c75cc",
 "version": "v0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
