
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cd955e9a46782119b36cc22b8dea5652ebbf9774",
 "version": "1.9.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
