# Version file autogenerated by the build process
version = '0.10.0-beta8'
build = 1093
vcs_info = 'Git SHA1 cb982709 committed on 2023-03-02'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.10.0-beta8"\nKSCONF_BUILD="1093"\nKSCONF_VCS_INFO="Git SHA1 cb982709 committed on 2023-03-02"')
